### ISSUE TITLE
Notch filter: picks < n_channels(67) got 67 -ERROR 

### ISSUE THREAD

**Issue by fannidkovacs** [mne-tools/mne-python#10258]
Hi!

- MNE version: 0.24.1
- operating system: Windows 10 Pro build number: 19041.1415

I had an issue using the mne.filter.notch_filter when I used it on my own data. The problem could be replicated.

```
from pathlib import Path

import mne



sample_dir = Path(mne.datasets.sample.data_path())

sample_fname = sample_dir / 'MEG' / 'sample' / 'sample_audvis_raw.fif'



raw = mne.io.read_raw_fif(sample_fname, preload=True)

raw.crop(tmax=60)

raw.set_channel_types(mapping={'EEG 001': 'ecg'})



emg_channel_pick = mne.pick_types(raw.info, emg=True) 

sampling_rate = raw.info['sfreq']

freqs = 50.0 

raw_filtered = mne.filter.notch_filter(raw, sampling_rate, freqs, picks=emg_channel_pick)
```

I tried add picks in several ways, unfortunatelly none of them worked, and always got the same error. 

```
Traceback (most recent call last):
  File "smthing.py", line 99, in <module>
    raw_filtered = mne.filter.notch_filter(raw, sampling_rate, freqs, picks='ecg')
  File "<decorator-gen-105>", line 24, in notch_filter
  File "C:\Anaconda\lib\site-packages\mne\filter.py", line 1190, in notch_filter
    xf = filter_data(x, Fs, highs, lows, picks, filter_length, tb_2, tb_2,
  File "<decorator-gen-103>", line 24, in filter_data
  File "C:\Anaconda\lib\site-packages\mne\filter.py", line 815, in filter_data
    data = _check_filterable(data)
  File "C:\Anaconda\lib\site-packages\mne\filter.py", line 1374, in _check_filterable
    x = np.asanyarray(x)
  File "C:\Anaconda\lib\site-packages\numpy\core\_asarray.py", line 136, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "C:\Anaconda\lib\site-packages\mne\io\base.py", line 807, in __getitem__
    return self._getitem(item)
  File "C:\Anaconda\lib\site-packages\mne\io\base.py", line 810, in _getitem
    sel, start, stop = self._parse_get_set_params(item)
  File "C:\Anaconda\lib\site-packages\mne\io\base.py", line 742, in _parse_get_set_params
    sel = _picks_to_idx(self.info, item[0])
  File "C:\Anaconda\lib\site-packages\mne\io\pick.py", line 1069, in _picks_to_idx
    raise ValueError('All picks must be < n_channels (%d), got %r'
ValueError: All picks must be < n_channels (67), got 67
```

Thank you for any help!

**Comment by larsoner** [comment]
`mne.filter.notch_filter` should only accept `np.ndarray` as the first argument, not `mne.io.Raw`. You should probably use `raw.notch_filter(...)` instead.

Let's keep this issue open, though, because we should do better input validation in `mne.filter.*` functions.

**Comment by fannidkovacs** [comment]
Thank you for the very fast reply!

When i was looking for a notch filter i could't find the `raw.notch_filter(...)` option, and it wasn't clear for me that `mne.filter.notch_filter` was only for `np.ndarray`.  But now everything worsk as it should, thank you.
