### ISSUE TITLE
Problem building the docs with psutil 5.9

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#10726]
Pretty sure this needs fixing upstream, but wanted to jot this down here as some kind of a reminder:

I currently cannot build the docs with `psutil` version 5.9; downgrading to 5.8 resolves the issue:
```python
❯ pwd
/Users/hoechenberger/Development/mne-python/doc
❯ PATTERN=40_sensor_locations.py make html_dev-pattern
[...]
generating gallery...

Traceback (most recent call last):
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/psutil/_common.py", line 442, in wrapper
    ret = self._cache[fun]
AttributeError: 'Process' object has no attribute '_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/psutil/_common.py", line 442, in wrapper
    ret = self._cache[fun]
AttributeError: 'Process' object has no attribute '_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/psutil/_psosx.py", line 343, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/psutil/_common.py", line 445, in wrapper
    return fun(self)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/psutil/_psosx.py", line 378, in _get_pidtaskinfo
    ret = cext.proc_pidtaskinfo_oneshot(self.pid)
ProcessLookupError: [Errno 3] No such process (originated from proc_pidinfo())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/sphinx_gallery/gen_gallery.py", line 461, in generate_gallery_rst
    gallery_conf = parse_config(app)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/sphinx_gallery/gen_gallery.py", line 124, in parse_config
    gallery_conf = _complete_gallery_conf(
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/sphinx_gallery/gen_gallery.py", line 216, in _complete_gallery_conf
    gallery_conf['memory_base'] = _get_memory_base(gallery_conf)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/sphinx_gallery/gen_rst.py", line 588, in _get_memory_base
    memories = memory_usage(proc, interval=1e-3, timeout=timeout)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/memory_profiler.py", line 403, in memory_usage
    mem_usage = _get_memory(
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/memory_profiler.py", line 219, in _get_memory
    return tools[backend]()
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/memory_profiler.py", line 138, in ps_util_tool
    mem = getattr(process, meminfo_attr)()[0] / _TWO_20
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/psutil/_common.py", line 445, in wrapper
    return fun(self)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/psutil/__init__.py", line 1058, in memory_info
    return self._proc.memory_info()
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/psutil/_psosx.py", line 343, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/psutil/_psosx.py", line 443, in memory_info
    rawtuple = self._get_pidtaskinfo()
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/psutil/_psosx.py", line 348, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=29118)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/sphinx/application.py", line 256, in __init__
    self._init_builder()
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/sphinx/application.py", line 315, in _init_builder
    self.events.emit('builder-inited')
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/sphinx/events.py", line 102, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function generate_gallery_rst at 0x1581d8f70> for event 'builder-inited' threw an exception (exception: process no longer exists (pid=29118))

Extension error (sphinx_gallery.gen_gallery):
Handler <function generate_gallery_rst at 0x1581d8f70> for event 'builder-inited' threw an exception (exception: process no longer exists (pid=29118))
Exception ignored in: <function Popen.__del__ at 0x104f07f40>
Traceback (most recent call last):
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/subprocess.py", line 1067, in __del__
    _warn("subprocess %s is still running" % self.pid,
ResourceWarning: subprocess 29118 is still running
make: *** [html_dev-pattern] Error 2
```

**Comment by hoechenberger** [comment]
Hmm, I'm occasionally seeing this error with 5.8 too, but it typically goes away when re-running sphinx. It was a constant problem with 5.9, however.

**Comment by larsoner** [comment]
I have never gotten `memory_profiler` + SG to work well on macOS :(

**Comment by agramfort** [comment]
same for me

**Comment by hoechenberger** [comment]
Ok I'll close this then, seems there's nothing we can really do about this for now.
