### ISSUE TITLE
import throws ModuleNotFoundError for 'seaborn'

### ISSUE THREAD

**Issue by girishmm** [mne-tools/mne-python#11860]
### Description of the problem

On install via pip, the expected behaviour is that all dependencies are installed and post-this, it is possible to import the module with `import mne_nirs`. But import throws a ModuleNotFoundError for 'seaborn'.

I have tried it twice to confirm it. First, using poetry (which uses pip internally). And then, directly using pip in a separate new environment. In both the case, the error was thrown.

On installing seaborn manually, the error goes away and normal functionality is restored.

### Steps to reproduce

```Python
Use pip to install mne-nirs. Open python shell and attempt to import.
```

### Expected results

```
>>> import mne_nirs
```

Returns with no error.

### Actual results

```
>>> import mne_nirs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/mne_nirs/__init__.py", line 10, in <module>
    from . import statistics
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/mne_nirs/statistics/__init__.py", line 7, in <module>
    from ._glm_level_first import (RegressionResults, ContrastResults,
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/mne_nirs/statistics/_glm_level_first.py", line 28, in <module>
    from ..visualisation._plot_GLM_topo import _plot_glm_topo,\
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/mne_nirs/visualisation/__init__.py", line 7, in <module>
    from ._plot_quality_metrics import plot_timechannel_quality_metric
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/mne_nirs/visualisation/_plot_quality_metrics.py", line 5, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
```

### Additional information

Platform             macOS-13.4-arm64-arm-64bit
Python               3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ]
Executable           /opt/homebrew/Caskroom/miniconda/base/bin/python
CPU                  arm (8 cores)
Memory               Unavailable (requires "psutil" package)
Core
├☑ mne               1.4.2
├☑ numpy             1.25.2 (OpenBLAS 0.3.23.dev with 8 threads)
├☑ scipy             1.11.1
├☑ matplotlib        3.7.2 (backend=MacOSX)
├☑ pooch             1.7.0
└☑ jinja2            3.1.2

Numerical (optional)
├☑ sklearn           1.3.0
├☑ nibabel           5.1.0
├☑ nilearn           0.10.1
├☑ pandas            2.0.3
└☐ unavailable       numba, dipy, openmeeg, cupy

Visualization (optional)
└☐ unavailable       pyvista, pyvistaqt, ipyvtklink, vtk, qtpy, ipympl, pyqtgraph, mne-qt-browser

Ecosystem (optional)
└☐ unavailable       mne-bids, mne-nirs, mne-features, mne-connectivity, mne-icalabel, mne-bids-pipeline

**Comment by larsoner** [comment]
This appears to be an issue with mne-nirs rather than MNE-Python so I'll transfer the issue over there!
