### ISSUE TITLE
mne.read_labels_from_annot

### ISSUE THREAD

**Issue by MegNParker** [mne-tools/mne-python#11882]
### Description of the problem

When I try to run the read_labels_from_annot faunction, it automatically adds "subject_id/label" to the end of my subjects_dir. However, this is not where my aseg.mgz file is saved. It is in the Freesurfer/Subjects/subject_id/mri folder. Is there a way to stop it from adding 'subject_id/label" to the end of my subjects_dir?

### Steps to reproduce

```Python
subject=sub-ABNUTCYL
subjects_dir="/home/stojek/bids_all_sessions/derivatives/freesurfer/subjects"

aseg_file=f"{subject_dir}/{subjid}//mri/aparc.a2009s+aseg.mgz"
      aseg_dir=f"{subject_dir}/{subjid}//mri/"
    vol_labels=mne.get_volume_labels_from_aseg(mgz_fname=aseg_file)
 #read in the labels.
    mne.read_labels_from_annot(subjid, subjects_dir=aseg_dir,parc='aparc.a2009s+aseg')
```

### Expected results

Reading labels from parcellation...
read X labels from /home/stojek/bids_all_sessions/derivatives/freesurfer/subjects/sub-ABNUTCYL/mri/aparc.a2009s+aseg.mgz

### Actual results

mne.read_labels_from_annot(subjid, subjects_dir=subjects_dir,parc='aparc.a2009s+aseg')
Reading labels from parcellation...
Traceback (most recent call last):

  File "/tmp/ipykernel_2922456/4104134062.py", line 1, in <cell line: 0>
    mne.read_labels_from_annot(subjid, subjects_dir=subjects_dir,parc='aparc.a2009s+aseg')

  File "<decorator-gen-381>", line 12, in read_labels_from_annot

  File "/home/stojek/miniconda3/envs/mne2/lib/python3.11/site-packages/mne/label.py", line 2325, in read_labels_from_annot
    annot, ctab, label_names = _read_annot(fname)

  File "/home/stojek/miniconda3/envs/mne2/lib/python3.11/site-packages/mne/label.py", line 2153, in _read_annot
    cands = _read_annot_cands(dir_name)

  File "/home/stojek/miniconda3/envs/mne2/lib/python3.11/site-packages/mne/label.py", line 2116, in _read_annot_cands
    raise OSError("Directory for annotation does not exist: %s", dir_name)

OSError: [Errno Directory for annotation does not exist: %s] /home/stojek/bids_all_sessions/derivatives/freesurfer/subjects/sub-ABNUTCYL/mri/sub-ABNUTCYL/label

### Additional information

Platform             Linux-5.15.0-71-generic-x86_64-with-glibc2.31
Python               3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
Executable           /home/stojek/miniconda3/envs/mne2/bin/python
CPU                  x86_64 (8 cores)
Memory               15.6 GB

Core
├☑ mne               1.4.2
├☑ numpy             1.24.4 (OpenBLAS 0.3.23 with 8 threads)
├☑ scipy             1.11.1
├☑ matplotlib        3.7.2 (backend=Qt5Agg)
├☑ pooch             1.7.0
└☑ jinja2            3.1.2

Numerical (optional)
├☑ sklearn           1.3.0
├☑ numba             0.57.1
├☑ nibabel           5.1.0
├☑ nilearn           0.10.1
├☑ dipy              1.7.0
├☑ openmeeg          2.5.6
├☑ pandas            2.0.3
└☐ unavailable       cupy

Visualization (optional)
├☑ pyvista           0.41.1 (OpenGL 3.3 (Core Profile) Mesa 21.2.6 via NVD9)
├☑ pyvistaqt         0.0.0
├☑ ipyvtklink        0.2.2
├☑ vtk               9.2.6
├☑ qtpy              2.3.1 (PyQt5=5.15.8)
├☑ pyqtgraph         0.13.3
├☑ mne-qt-browser    0.5.2
└☐ unavailable       ipympl

Ecosystem (optional)
├☑ mne-bids          0.12
└☐ unavailable       mne-nirs, mne-features, mne-connectivity, mne-icalabel, mne-bids-pipeline

**Comment by larsoner** [comment]
`read_labels_from_annot` only reads surface `.annot` files from `subject_id/lables/*.annot`, it does not read `.mgz` volumetric files.

For further discussion please start a new thread on https://mne.discourse.group/ because this seems more like a usage issue than one about MNE-Python's code itself!
