### ISSUE TITLE
How to build the documentation?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#12590]
I installed via `pip install -e ".[doc]"` but I cannot build the docs:

```python
❯ pwd
/Users/richardhochenberger/Development-new/mne-python/doc
❯ make html-pattern PATTERN=70_report
sphinx-build -D sphinx_gallery_conf.filename_pattern=70_report -D sphinx_gallery_conf.run_stale_examples=True -b html -d _build/doctrees -nWT --keep-going . _build/html
Running Sphinx v7.2.6
Building documentation for MNE 1.8.0.dev45+g6162214d2.d20240430 (/Users/richardhochenberger/Development-new/mne-python/mne/__init__.py)
Using pyvistaqt 3d backend.


Traceback (most recent call last):
  File "/Users/richardhochenberger/mambaforge/envs/mne/lib/python3.11/site-packages/sphinx_gallery/gen_gallery.py", line 261, in _fill_gallery_conf_defaults
    scraper = import_module(scraper)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richardhochenberger/mambaforge/envs/mne/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1135, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mne_doc_utils.gui_scraper'; 'mne_doc_utils' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/richardhochenberger/mambaforge/envs/mne/lib/python3.11/site-packages/sphinx/cmd/build.py", line 293, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richardhochenberger/mambaforge/envs/mne/lib/python3.11/site-packages/sphinx/application.py", line 257, in __init__
    self.events.emit('config-inited', self.config)
  File "/Users/richardhochenberger/mambaforge/envs/mne/lib/python3.11/site-packages/sphinx/events.py", line 97, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richardhochenberger/mambaforge/envs/mne/lib/python3.11/site-packages/sphinx_gallery/gen_gallery.py", line 1507, in fill_gallery_conf_defaults
    new_sphinx_gallery_conf = _fill_gallery_conf_defaults(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richardhochenberger/mambaforge/envs/mne/lib/python3.11/site-packages/sphinx_gallery/gen_gallery.py", line 265, in _fill_gallery_conf_defaults
    raise ConfigError(
sphinx.errors.ConfigError: Unknown image scraper 'mne_doc_utils.gui_scraper', got:
No module named 'mne_doc_utils.gui_scraper'; 'mne_doc_utils' is not a package

Configuration error:
Unknown image scraper 'mne_doc_utils.gui_scraper', got:
No module named 'mne_doc_utils.gui_scraper'; 'mne_doc_utils' is not a package
make: *** [html-pattern] Error 2
```
What's the problem here?

**Comment by larsoner** [comment]
You need the latest sphinx-gallery release or `master`

**Comment by hoechenberger** [comment]
That means that we need to set a lower boundary for Sphinx gallery in pyproject.toml, no?

**Comment by larsoner** [comment]
Sure, added in #12588
