### ISSUE TITLE
ValueError: Points have to be provided as one dimensional arrays of length 3.

### ISSUE THREAD

**Issue by Whit3Zhao** [mne-tools/mne-python#12632]
### Description of the problem

Hi, this is my problem, my dataset is BCICIV 2b and I preprocess my data and my data's shape is [160, 6, 750], then i divide my data in axis 1 ,and concat my data in dim=0 so, my shape become [320, 3, 750] 
import mne

    biosemi_montage = mne.channels.make_standard_montage('biosemi64')
    index = [12, 47, 49]  # for bci competition iv 2b
    this index is C3 Cz C4
    biosemi_montage.ch_names = [biosemi_montage.ch_names[i] for i in index]
    biosemi_montage.dig = [biosemi_montage.dig[i + 3] for i in index]
    info = mne.create_info(ch_names=biosemi_montage.ch_names, sfreq=250., ch_types='eeg')
    other code......
    evoked = mne.EvokedArray(mean_target_data, info=info)
    evoked.set_montage(biosemi_montage)
this picture is my attribute about biosemi_montage
![image](https://github.com/mne-tools/mne-python/assets/171122743/b1f3187a-0386-458c-b446-a9bbaca47b15)
when my program execute in evoked.set_montage(biosemi_montage) my program disrupt

### Steps to reproduce

```Python
def preprocess(data_file, stage='test'):
    print(f'loading data from: {data_file}')
    # 加载mat格式的文件
    data = io.loadmat(data_file)
    # label numbers must start at 0
    # EEG_data original shape is [22, 1000, 288] and label shape is [288, 1]
    #EEG = data['EEG_data'].astype(np.float64) # 2a data tag
    EEG = data['data_set'].astype(np.float64) # 2b data tag
    # shape change to [288, 22, 1000]
    EEG = EEG.transpose((2, 0, 1))
    # shape change to [288,]
    labels = data['labels_set'].reshape(-1).astype(np.int32) # 2b labels tag
    #labels = data['label'].reshape(-1).astype(np.int32)  # N 2a labels tag
    # index start from 0
    labels = labels - np.min(labels)

    # filter bank signals
    EEG_bank = []
    for bank in config.filter_bank:
        parameter = signal.butter(N=5, Wn=bank, btype='bandpass', fs=config.fs)
        EEG_filtered = signal.lfilter(parameter[0], parameter[1], EEG)[...,
                       config.ref_dur * config.fs::config.resample]
        EEG_bank.append(EEG_filtered)
    # event number is same , channels are merged, sample is same
    EEG = np.concatenate(EEG_bank, axis=1).astype(np.float32)  # N,F*C,T
    EEG = (EEG - config.mean) / config.std
    print(f'preprocessing data: {EEG.shape} {labels.shape}')
    # print(np.max(EEG))
    # return shape is [288, 22 * 2, 1000]
    return EEG, labels
def reshape_transform(tensor):
    return tensor.unsqueeze(1)
def main():
    train_datasets = build_datasets_files(stage='Test')  # file list in subject list
    subject = train_datasets[0][0].split('/')[-2]
    models = torch.load(f'{config.output}/models/{subject}_{config.tag}.pth',
                        map_location=f'cuda:{torch.cuda.current_device()}')
    dataset_path = train_datasets[0][0]
    data, labels = preprocess(dataset_path, 'Test')
    data, labels = window_split(torch.from_numpy(data).cuda(), torch.from_numpy(labels).long().cuda())

    target_index = torch.where(labels == 1)
    target_data = data[target_index]
    print(target_data.shape)
    model = models.pop(0)
    target_layers = [model.fc]
    cam = GradCAM(model=model, target_layers=target_layers, use_cuda=True, reshape_transform=reshape_transform)
    import mne

    biosemi_montage = mne.channels.make_standard_montage('biosemi64')
    index = [12, 47, 49]  # for bci competition iv 2b
    #biosemi_montage.ch_names = biosemi_montage.ch_names[:3]
    #biosemi_montage.dig = biosemi_montage.dig[:6]

    biosemi_montage.ch_names = [biosemi_montage.ch_names[i] for i in index]
    print(biosemi_montage.ch_names)
    biosemi_montage.dig = [biosemi_montage.dig[i + 3] for i in index]
    print(biosemi_montage.dig)
    info = mne.create_info(ch_names=biosemi_montage.ch_names, sfreq=250., ch_types='eeg')

    all_cam = []
    # this loop is used to obtain the cam of each trial/sample
    for i in range(len(target_data)):
        test = torch.as_tensor(target_data[i:i + 1], dtype=torch.float32)
        test = torch.autograd.Variable(test, requires_grad=True)
        grayscale_cam = cam(input_tensor=test, target_category=1)
        grayscale_cam = grayscale_cam[0, :]
        grayscale_cam = np.array_split(grayscale_cam, 2, 0)
        for j in range(2):
            all_cam.append(grayscale_cam[j])
        #all_cam.append(grayscale_cam)

    if isinstance(target_data, torch.Tensor):
        target_data = target_data.cpu().numpy()
    if isinstance(all_cam, torch.Tensor):
        all_cam = all_cam.cpu().numpy()
    # the mean of all target data
    target_data = np.array_split(target_data, 2, 1)
    target_data = numpy.concatenate((target_data[0], target_data[1]), axis=0)

    mean_target_data = np.mean(target_data, axis=0)  # N*C*T -> C*T
    norm_mean_target_data = (mean_target_data - np.mean(mean_target_data)) / np.std(mean_target_data)
    vis_target_data = np.mean(norm_mean_target_data, axis=1)  # C*T -> C

    # the mean of all cam
    mean_all_cam = np.mean(all_cam, axis=0)  # N*1*T -> 1*T

    # apply cam on the input data
    hyb_all = mean_target_data * mean_all_cam
    hyb_all = (hyb_all - np.mean(hyb_all)) / np.std(hyb_all)
    vis_hyb_all = np.mean(hyb_all, axis=1)

    evoked = mne.EvokedArray(mean_target_data, info=info)
    evoked.set_montage(biosemi_montage)
    fig, [ax1, ax2] = plt.subplots(nrows=2)

    # print(mean_all_test)
    plt.subplot(211)
    im, cn1 = mne.viz.plot_topomap(vis_target_data, evoked.info, show=False, axes=ax1, res=1200)

    plt.subplot(212)
    im, cn2 = mne.viz.plot_topomap(vis_hyb_all, evoked.info, show=False, axes=ax2, res=1200)
    plt.show()

    plt.close()
```

### Expected results

print the viusalize picture

### Actual results

Traceback (most recent call last):
File "E:\DeveloperTools\PyCharm 2023.1.3\plugins\python\helpers\pydev\pydevd.py", line 1496, in _exec
pydev_imports.execfile(file, globals, locals) # execute the script
File "E:\DeveloperTools\PyCharm 2023.1.3\plugins\python\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "E:\PycharmProjects\bcicIV2a\TestNet\visualize_2a.py", line 116, in
main()
File "E:\PycharmProjects\bcicIV2a\TestNet\visualize_2a.py", line 98, in main
evoked.set_montage(biosemi_montage)
File "<E:\Anaconda\lib\site-packages\mne\externals\decorator.py:decorator-gen-30>", line 2, in set_montage
File "E:\Anaconda\lib\site-packages\mne\utils_logging.py", line 90, in wrapper
return function(*args, **kwargs)
File "E:\Anaconda\lib\site-packages\mne\channels\channels.py", line 487, in set_montage
_set_montage(self.info, montage, update_ch_names=DEPRECATED_PARAM,
File "E:\Anaconda\lib\site-packages\mne\channels\montage.py", line 1545, in _set_montage
_mnt = _get_montage_in_head(montage)
File "E:\Anaconda\lib\site-packages\mne\channels\montage.py", line 1356, in _get_montage_in_head
return transform_to_head(montage.copy())
File "E:\Anaconda\lib\site-packages\mne\channels\montage.py", line 935, in transform_to_head
native_head_t = get_ras_to_neuromag_trans(nasion, lpa, rpa)
File "E:\Anaconda\lib\site-packages\mne\transforms.py", line 650, in get_ras_to_neuromag_trans
raise ValueError("Points have to be provided as one dimensional "
ValueError: Points have to be provided as one dimensional arrays of length 3.
python-BaseException

process exit, code 1

### Additional information

Platform:      Windows-10-10.0.22631-SP0
Python:        3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
Executable:    E:\Anaconda\python.exe
CPU:           Intel64 Family 6 Model 151 Stepping 2, GenuineIntel: 16 cores
Memory:        31.9 GB

mne:           0.19.2
numpy:         1.23.5 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.10.0
matplotlib:    3.7.0 {backend=module://backend_interagg}

sklearn:       1.2.1
numba:         0.56.4
nibabel:       Not found
cupy:          Not found
pandas:        1.5.3
dipy:          Not found
mayavi:        Not found
pyvista:       Not found
vtk:           Not found
None

**Comment by Whit3Zhao** [comment]
Hi, i solve this problem i update my mne this error is solved

![image](https://github.com/mne-tools/mne-python/assets/171122743/1a9ba6aa-5610-468a-ab12-6c15b618f362)
