### ISSUE TITLE
Cannot build HTML docs

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#12653]
```python
$ make html
sphinx-build -b html -d _build/doctrees -nWT --keep-going . _build/html
Running Sphinx v7.3.7
Building documentation for MNE 1.8.0.dev113+g0b7bd34fa.d20240608 (/workspaces/mne-python/mne/__init__.py)
Using pyvistaqt 3d backend.
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
loading pickled environment... checking bibtex cache... up to date
done
[autosummary] generating autosummary for: api/connectivity.rst, api/covariance.rst, api/creating_from_arrays.rst, api/datasets.rst, api/decoding.rst, api/events.rst, api/export.rst, api/file_io.rst, api/forward.rst, api/inverse.rst, ..., install/manual_install.rst, install/manual_install_python.rst, install/mne_c.rst, install/mne_tools_suite.rst, install/updating.rst, martinos.rst, mne_cpp.rst, old_versions/index.rst, overview/people.rst, sg_execution_times.rst
generating gallery...
generating gallery for auto_tutorials... 
generating gallery for auto_tutorials/intro... [ 14%] 10_overview.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/sphinx/events.py", line 97, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/sphinx_gallery/gen_gallery.py", line 616, in generate_gallery_rst
    ) = generate_dir_rst(src_dir, target_dir, gallery_conf, seen_backrefs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/sphinx_gallery/gen_rst.py", line 539, in generate_dir_rst
    intro, title, (t, mem) = generate_file_rst(
                             ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/sphinx_gallery/gen_rst.py", line 1210, in generate_file_rst
    clean_modules(gallery_conf, fname, "before")
  File "/opt/conda/lib/python3.12/site-packages/sphinx_gallery/scrapers.py", line 563, in clean_modules
    reset_module(gallery_conf, fname, when=when)
  File "/workspaces/mne-python/doc/sphinxext/mne_doc_utils.py", line 173, in reset_modules
    from mne_qt_browser._pg_figure import MNEQtBrowser
  File "/opt/conda/lib/python3.12/site-packages/mne_qt_browser/_pg_figure.py", line 37, in <module>
    from colorspacious import cspace_convert
  File "/opt/conda/lib/python3.12/site-packages/colorspacious/__init__.py", line 17, in <module>
    from .comparison import deltaE
  File "/opt/conda/lib/python3.12/site-packages/colorspacious/comparison.py", line 11
    """Computes the :math:`\Delta E` distance between pairs of colors.
    ^^^
SyntaxError: invalid escape sequence '\D'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/sphinx/application.py", line 268, in __init__
    self._init_builder()
  File "/opt/conda/lib/python3.12/site-packages/sphinx/application.py", line 339, in _init_builder
    self.events.emit('builder-inited')
  File "/opt/conda/lib/python3.12/site-packages/sphinx/events.py", line 108, in emit
    raise ExtensionError(
sphinx.errors.ExtensionError: Handler <function generate_gallery_rst at 0xffff448982c0> for event 'builder-inited' threw an exception (exception: invalid escape sequence '\D' (comparison.py, line 11))

Extension error (sphinx_gallery.gen_gallery):
Handler <function generate_gallery_rst at 0xffff448982c0> for event 'builder-inited' threw an exception (exception: invalid escape sequence '\D' (comparison.py, line 11))
make: *** [Makefile:34: html] Error 2
```
Any idea what's up?

Using `colorspacious` 1.1.2

**Comment by hoechenberger** [comment]
> Using `colorspacious` 1.1.2

… released in 2018 or so. That project is deader than dead…

https://github.com/njsmith/colorspacious
