### ISSUE TITLE
loosevar orientation constraint 

### ISSUE THREAD

**Issue by dgwakeman** [mne-tools/mne-python#1303]
We are getting some strange behavior when using loosevar orientation constrained solutions in mne-python. We can read them in and apply them; however if we use: ``pick_ori='normal'`` we get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in apply_inverse_raw
  File "mne/utils.py", line 392, in verbose
  File "mne/minimum_norm/inverse.py", line 855, in apply_inverse_raw
  File "<string>", line 2, in _assemble_kernel
  File "mne/utils.py", line 392, in verbose
  File "mne/minimum_norm/inverse.py", line 639, in _assemble_kernel
TypeError: 'NoneType' object has no attribute '__getitem__'

Any thoughts? (reporting for a friend)

**Comment by Eric89GXL** [comment]
Haven't heard back in about a year, closing for now. Feel free to reopen if this comes up again.
