### ISSUE TITLE
FAIL: Test adding distances to source space  

### ISSUE THREAD

**Issue by mluessi** [mne-tools/mne-python#1449]
I'm getting a failing test:

    ======================================================================
    FAIL: Test adding distances to source space                           
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/autofs/cluster/pubsw/2/pubsw/Linux2-2.3-x86_64/packages/python/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
    File "/autofs/cluster/pubsw/2/pubsw/Linux2-2.3-x86_64/packages/python/anaconda/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
        return f(*args, **kwargs)
    File "/autofs/cluster/pubsw/2/pubsw/Linux2-2.3-x86_64/packages/python/anaconda/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
        return f(*args, **kwargs)
    File "/autofs/space/megmix_002/users/mluessi/data/code/mne-python/mne-python/mne/tests/test_source_space.py", line 138, in test_add_source_space_distances
        assert_array_equal(so['dist_limit'], np.array([-0.007], np.float32))
    File "/autofs/cluster/pubsw/2/pubsw/Linux2-2.3-x86_64/packages/python/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 719, in assert_array_equal
        verbose=verbose, header='Arrays are not equal')
    File "/autofs/cluster/pubsw/2/pubsw/Linux2-2.3-x86_64/packages/python/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 645, in assert_array_compare
        raise AssertionError(msg)
    AssertionError:
    Arrays are not equal

    (mismatch 100.0%)
    x: array(None, dtype=object)
    y: array([-0.007], dtype=float32)

**Comment by teonlamont** [comment]
is this fixed?

**Comment by Eric89GXL** [comment]
Should be, I think it was just a case of an outdated sample dataset
