### ISSUE TITLE
BUG: Covariance calculation in newer numpy

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#2089]
I am getting a bug with newest `numpy`:
```
======================================================================
ERROR: Test cov regularization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/larsoner/custombuilds/mne-python/mne/tests/test_cov.py", line 240, in test_regularize_cov
    exclude='bads')
  File "/home/larsoner/custombuilds/mne-python/mne/cov.py", line 1314, in regularize
    cov['data'][np.ix_(idx, idx)] = C
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy/lib/index_tricks.py", line 77, in ix_
    raise ValueError("Cross index must be 1 dimensional")
ValueError: Cross index must be 1 dimensional
```
I think the indexing tricks are not meant to be used in production code, so we should probably switch to `np.concatenate`. @dengemann okay with you?

**Comment by Eric89GXL** [comment]
Ahh, nevermind it's `ix_` not `r_`. I'll see if I can fix it...

**Comment by Eric89GXL** [comment]
Seems to be some oddity due to running bleeding-edge `numpy`. Closing for now assuming it's their bug not ours.
