### ISSUE TITLE
TVTK requirement for building high res surfs

### ISSUE THREAD

**Issue by jona-sassenhagen** [mne-tools/mne-python#3435]
Running `mne make_scalp_surfaces` on a Mac, I get

```
3. Creating medium tessellation...
3.1 Decimating the dense tessellation...
Traceback (most recent call last):
  File "/Users/jona/anaconda3/envs/py2/lib/python2.7/site-packages/mne-0.13.dev0-py2.7.egg/mne/commands/mne_make_scalp_surfaces.py", line 144, in <module>
    run()
  File "/Users/jona/anaconda3/envs/py2/lib/python2.7/site-packages/mne-0.13.dev0-py2.7.egg/mne/commands/mne_make_scalp_surfaces.py", line 56, in run
    options.verbose)
  File "<string>", line 2, in _run
  File "/Users/jona/anaconda3/envs/py2/lib/python2.7/site-packages/mne-0.13.dev0-py2.7.egg/mne/utils.py", line 667, in verbose
    return function(*args, **kwargs)
  File "/Users/jona/anaconda3/envs/py2/lib/python2.7/site-packages/mne-0.13.dev0-py2.7.egg/mne/commands/mne_make_scalp_surfaces.py", line 127, in _run
    n_triangles=n_tri)
  File "/Users/jona/anaconda3/envs/py2/lib/python2.7/site-packages/mne-0.13.dev0-py2.7.egg/mne/surface.py", line 834, in decimate_surface
    return _decimate_surface(points, triangles, reduction)
  File "/Users/jona/anaconda3/envs/py2/lib/python2.7/site-packages/mne-0.13.dev0-py2.7.egg/mne/surface.py", line 791, in _decimate_surface
    raise ValueError('This function requires the TVTK package to be '
ValueError: This function requires the TVTK package to be installed
```

**Comment by Eric89GXL** [comment]
This should only happen if decimation is requested, I'll fix it

**Comment by Eric89GXL** [comment]
...looks like decimation is mandatory, I'll probably make an argument to supply the decimation levels

**Comment by Eric89GXL** [comment]
Or since they're called "medium" and "sparse", maybe just `--nodecimate` would do it
