### ISSUE TITLE
BUG: Round-trip FIF IO broken when `concatenate_raws` is used

### ISSUE THREAD

**Issue by Eric89GXL** [mne-tools/mne-python#4164]
This:
```
>>> import mne
>>> fname = mne.datasets.sample.data_path() + '/MEG/sample/sample_audvis_raw.fif'
>>> raw = mne.io.read_raw_fif(fname)
>>> raw = mne.concatenate_raws([raw])
>>> raw.save('test_raw.fif', overwrite=True)
>>> raw_read = mne.io.read_raw_fif('test_raw.fif')
Traceback (most recent call last):
  File "/home/larsoner/Desktop/untitled4.py", line 14, in <module>
    raw_read = mne.io.read_raw_fif('test_raw.fif')
  File "/home/larsoner/custombuilds/mne-python/mne/io/fiff/raw.py", line 476, in read_raw_fif
    preload=preload, verbose=verbose)
  File "<string>", line 2, in __init__
  File "/home/larsoner/custombuilds/mne-python/mne/utils.py", line 707, in verbose
    return function(*args, **kwargs)
  File "/home/larsoner/custombuilds/mne-python/mne/io/fiff/raw.py", line 81, in __init__
    preload, do_check_fname)
  File "<string>", line 2, in _read_raw_file
  File "/home/larsoner/custombuilds/mne-python/mne/utils.py", line 707, in verbose
    return function(*args, **kwargs)
  File "/home/larsoner/custombuilds/mne-python/mne/io/fiff/raw.py", line 165, in _read_raw_file
    duration = tag.data - onset
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```
There are actually two bugs here, which you can see from this traceback plus the last bit of `show_fiff` on the offending file:
```
larsoner@bunk:~/Desktop$ mne show_fiff test_raw.fif 
...
            359 = FIFFB_MNE_BAD_CHANNELS
                3507 = FIFF_MNE_CH_NAME_LIST (16) = MEG 2443:EEG 053 ... str len=16
        3810 = FIFFB_MNE_ANNOTATIONS
            3568 = FIFF_MNE_BASELINE_MIN (0)
            3569 = FIFF_MNE_BASELINE_MAX (0)
        102 = FIFFB_RAW_DATA
            208 = FIFF_FIRST_SAMPLE (4) = [25800]
            x278: 300 = FIFF_DATA_BUFFER (902400) = [  1.22070312e-03  -3.05175781 ... array size=225600
```
Bugs:

1. Annotations should not be written if none are present in the original file.
2. Annotations writing has some bug where `kind == FIFF.FIFF_MNE_BASELINE_MAX` but the `tag.data is None`.

**Comment by Eric89GXL** [comment]
cc @kambysese

**Comment by Eric89GXL** [comment]
@jaeilepp do you have time to look since it appears related to Annotations? If not, I can look tomorrow.
