### ISSUE TITLE
error: coreg trans cannot save

### ISSUE THREAD

**Issue by kingjr** [mne-tools/mne-python#4262]
I'm trying to save a trans file after scaling, translating and rotating an mri to fit my eeg electrodes.

I get this error:
```
Error scaling eeg_manual2-trans:
Traceback (most recent call last):
  File "/home/jrking/git/mne-python/mne/gui/_coreg_gui.py", line 848, in worker
    include_annot)
  File "/home/jrking/git/mne-python/mne/coreg.py", line 1078, in scale_mri
    scale_bem(subject_to, bem_name, subject_from, scale, subjects_dir)
  File "/home/jrking/git/mne-python/mne/coreg.py", line 950, in scale_bem
    surf['nn'] *= nn_scale
ValueError: operands could not be broadcast together with shapes (0,) (3,) 

```

I'm not sure what i'm supposed to do.

cc @Eric89GXL @christianbrodbeck

**Comment by christianbrodbeck** [comment]
Looks your source space does no have normals, I assume we never ran into this situation
