### ISSUE TITLE
Points not visible in mne_gui_coregistration()

### ISSUE THREAD

**Issue by jshanna100** [mne-tools/mne-python#4728]
MNE 0.15 running on Python 3.5.4 and Mayavi 4.5.0

I have EEG data with fiducials, channel locations, and skin points defined with a 3D localiser. These were converted to a Digital Montage, and applied to the EEG raw fif file. Viewing with mne.viz.plot_alignment() seems to confirm that this was correctly done (see image), but it just needs to be aligned with the MRI fiducials. Therein lies the problem: mne.gui.coregistration() does not plot the points (see image). The points do seem to be read into the programme, as fitting functions work without problem, but they just are not visualised at all.

![snapshot](https://user-images.githubusercontent.com/22842307/32406755-a520557a-c17e-11e7-88b8-c3bcf1c0635c.png)

![image](https://user-images.githubusercontent.com/22842307/32406769-dceef722-c17e-11e7-9085-812918473eb3.png)

**Comment by jshanna100** [comment]
Also produces the following error message upon start; programme does not terminate however:

mne.gui.coregistration(subjects_dir="/home/jeff/mrisubs",subject="sub1")
Exception occurred in traits notification handler for object: <mne.gui._viewer.PointObject object at 0x7f193ca5efc0>, trait: scene, old value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f1950329308>, new value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f1931f71bf8>
Traceback (most recent call last):
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/mne/gui/_viewer.py", line 225, in _plot_points
    if not self.scene.running():
AttributeError: 'MlabSceneModel' object has no attribute 'running'
Exception occurred in traits notification handler for object: <mne.gui._viewer.PointObject object at 0x7f195032eaf0>, trait: scene, old value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f195032eba0>, new value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f1931f71bf8>
Traceback (most recent call last):
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/mne/gui/_viewer.py", line 225, in _plot_points
    if not self.scene.running():
AttributeError: 'MlabSceneModel' object has no attribute 'running'
Exception occurred in traits notification handler for object: <mne.gui._viewer.PointObject object at 0x7f192bf75a98>, trait: scene, old value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f192bf75ca8>, new value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f1931f71bf8>
Traceback (most recent call last):
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/mne/gui/_viewer.py", line 225, in _plot_points
    if not self.scene.running():
AttributeError: 'MlabSceneModel' object has no attribute 'running'
Exception occurred in traits notification handler for object: <mne.gui._viewer.PointObject object at 0x7f195032ee60>, trait: scene, old value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f195032ef10>, new value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f1931f71bf8>
Traceback (most recent call last):
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/mne/gui/_viewer.py", line 225, in _plot_points
    if not self.scene.running():
AttributeError: 'MlabSceneModel' object has no attribute 'running'
Exception occurred in traits notification handler for object: <mne.gui._viewer.PointObject object at 0x7f193ca4f200>, trait: scene, old value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f193ca4f2b0>, new value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f1931f71bf8>
Traceback (most recent call last):
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/mne/gui/_viewer.py", line 225, in _plot_points
    if not self.scene.running():
AttributeError: 'MlabSceneModel' object has no attribute 'running'
Exception occurred in traits notification handler for object: <mne.gui._viewer.PointObject object at 0x7f193ca4f570>, trait: scene, old value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f193ca4f620>, new value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f1931f71bf8>
Traceback (most recent call last):
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/mne/gui/_viewer.py", line 225, in _plot_points
    if not self.scene.running():
AttributeError: 'MlabSceneModel' object has no attribute 'running'
Exception occurred in traits notification handler for object: <mne.gui._viewer.PointObject object at 0x7f193ca4f8e0>, trait: scene, old value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f193ca4f990>, new value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f1931f71bf8>
Traceback (most recent call last):
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/mne/gui/_viewer.py", line 225, in _plot_points
    if not self.scene.running():
AttributeError: 'MlabSceneModel' object has no attribute 'running'
Exception occurred in traits notification handler for object: <mne.gui._viewer.PointObject object at 0x7f193ca4fc50>, trait: scene, old value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f193ca4fd00>, new value: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7f1931f71bf8>
Traceback (most recent call last):
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/home/jeff/anaconda3/lib/python3.5/site-packages/mne/gui/_viewer.py", line 225, in _plot_points
    if not self.scene.running():
AttributeError: 'MlabSceneModel' object has no attribute 'running'
Out[65]: <mne.gui._coreg_gui.CoregFrame at 0x7f1931f30db0>

**Comment by larsoner** [comment]
Can you try latest `master`? The "running" problem should be fixed there

**Comment by larsoner** [comment]
(and the "running" problem could be causing the bad plotting)

**Comment by jshanna100** [comment]
Yes, with 0.16 it is fixed. An alternate hack is commenting out the if statement at line 225 in _plot_points. Thanks!

**Comment by agramfort** [comment]
did we already backport this fix?

**Comment by larsoner** [comment]
Yes in https://github.com/mne-tools/mne-python/commit/f61dc99dba575eddad7360bc98cb88306aa1af44
