### ISSUE TITLE
Unable to save fif file

### ISSUE THREAD

**Issue by asmasbaih3000** [mne-tools/mne-python#5289]
Dear Sir or Madame,

I am using mne-python and try to load and save raw fif-files. I successfully loaded the data, but somehow saving the file is NOT working. The same code sample runs on my college's machine just fine. the only difference is the version of mne-python he is using.

Here is some code snippet that illustrates the error:
```
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import mne
mne.__version__

fname = '/home/asbaih/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif'
raw = mne.io.read_raw_fif(fname, preload=True)

raw.plot(n_channels=40, duration=50)

raw.save(fname, overwrite=True)
```

Here is the error:
```
Traceback (most recent call last):

  File "<ipython-input-209-365f46b743cc>", line 12, in <module>
    raw.save(fname, overwrite=True)

  File "<string>", line 2, in save

  File "/home/asbaih/anaconda2/lib/python2.7/site-packages/mne/utils.py", line 729, in verbose
    return function(*args, **kwargs)

  File "/home/asbaih/anaconda2/lib/python2.7/site-packages/mne/io/base.py", line 1749, in save
    split_size, 0, None)

  File "/home/asbaih/anaconda2/lib/python2.7/site-packages/mne/io/base.py", line 2179, in _write_raw
    reset_range, raw.annotations)

  File "/home/asbaih/anaconda2/lib/python2.7/site-packages/mne/io/base.py", line 2331, in _start_writing_raw
    fid = start_file(name)

  File "/home/asbaih/anaconda2/lib/python2.7/site-packages/mne/io/write.py", line 277, in start_file
    write_id(fid, FIFF.FIFF_FILE_ID, id_)

  File "/home/asbaih/anaconda2/lib/python2.7/site-packages/mne/io/write.py", line 229, in write_id
    fid.write(np.array(kind, dtype='>i4').tostring())

IOError: File not open for writing
```

I am grateful for any help.

Yours sincerely,
A. Sbaih

**Comment by asmasbaih3000** [comment]
I solved the problem.
thank you
