### ISSUE TITLE
PySurfer and Twisted installation issues   

### ISSUE THREAD

**Issue by zachs321** [mne-tools/mne-python#5479]
When following your installation instructions I get the following error:

```
Zacharys-MacBook-Pro:~ zacharystow$ curl -O https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   485  100   485    0     0   1971      0 --:--:-- --:--:-- --:--:--  1971
Zacharys-MacBook-Pro:~ zacharystow$ conda env create -f environment.yml
Solving environment: done

Downloading and Extracting Packages
wcwidth-0.1.7        | 25 KB     | ######################################################################################################################## | 100% 
sphinxcontrib-1.0    | 3 KB      | ######################################################################################################################## | 100% 
wheel-0.31.1         | 62 KB     | ######################################################################################################################## | 100% 
libcxxabi-4.0.1      | 149 KB    | ######################################################################################################################## | 100% 
statsmodels-0.9.0    | 8.5 MB    | ######################################################################################################################## | 100% 
libiconv-1.15        | 1.3 MB    | ######################################################################################################################## | 100% 
astroid-2.0.4        | 247 KB    | ######################################################################################################################## | 100% 
cffi-1.11.5          | 205 KB    | ######################################################################################################################## | 100% 
decorator-4.3.0      | 15 KB     | ######################################################################################################################## | 100% 
pyqt-5.9.2           | 4.7 MB    | ######################################################################################################################## | 100% 
keyring-13.2.1       | 46 KB     | ######################################################################################################################## | 100% 
pygments-2.2.0       | 1.3 MB    | ######################################################################################################################## | 100% 
pandocfilters-1.4.2  | 13 KB     | ######################################################################################################################## | 100% 
attrs-18.1.0         | 43 KB     | ######################################################################################################################## | 100% 
numexpr-2.6.8        | 126 KB    | ######################################################################################################################## | 100% 
cloudpickle-0.5.5    | 26 KB     | ######################################################################################################################## | 100% 
libffi-3.2.1         | 40 KB     | ######################################################################################################################## | 100% 
backcall-0.1.0       | 19 KB     | ######################################################################################################################## | 100% 
appdirs-1.4.3        | 16 KB     | ######################################################################################################################## | 100% 
jedi-0.12.1          | 225 KB    | ######################################################################################################################## | 100% 
imagesize-1.0.0      | 8 KB      | ######################################################################################################################## | 100% 
mistune-0.8.3        | 244 KB    | ######################################################################################################################## | 100% 
automat-0.7.0        | 52 KB     | ######################################################################################################################## | 100% 
kiwisolver-1.0.1     | 56 KB     | ######################################################################################################################## | 100% 
python-dateutil-2.7. | 260 KB    | ######################################################################################################################## | 100% 
cython-0.28.5        | 3.0 MB    | ######################################################################################################################## | 100% 
simplegeneric-0.8.1  | 9 KB      | ######################################################################################################################## | 100% 
expat-2.2.6          | 129 KB    | ######################################################################################################################## | 100% 
pickleshare-0.7.4    | 12 KB     | ######################################################################################################################## | 100% 
terminado-0.8.1      | 21 KB     | ######################################################################################################################## | 100% 
appnope-0.1.0        | 8 KB      | ######################################################################################################################## | 100% 
pytest-cov-2.5.1     | 25 KB     | ######################################################################################################################## | 100% 
pyparsing-2.2.0      | 96 KB     | ######################################################################################################################## | 100% 
cycler-0.10.0        | 13 KB     | ######################################################################################################################## | 100% 
glib-2.56.2          | 4.7 MB    | ######################################################################################################################## | 100% 
tk-8.6.8             | 3.2 MB    | ######################################################################################################################## | 100% 
libcxx-4.0.1         | 957 KB    | ######################################################################################################################## | 100% 
ptyprocess-0.6.0     | 23 KB     | ######################################################################################################################## | 100% 
patsy-0.5.0          | 322 KB    | ######################################################################################################################## | 100% 
spyder-3.3.1         | 2.6 MB    | ######################################################################################################################## | 100% 
coverage-4.5.1       | 209 KB    | ######################################################################################################################## | 100% 
joblib-0.12.2        | 334 KB    | ######################################################################################################################## | 100% 
freetype-2.8         | 840 KB    | ######################################################################################################################## | 100% 
isort-4.3.4          | 58 KB     | ######################################################################################################################## | 100% 
vtk-8.1.0            | 28.4 MB   | ######################################################################################################################## | 100% 
libedit-3.1.20170329 | 154 KB    | ######################################################################################################################## | 100% 
prompt_toolkit-1.0.1 | 339 KB    | ######################################################################################################################## | 100% 
spyder-kernels-0.2.6 | 69 KB     | ######################################################################################################################## | 100% 
qtpy-1.5.0           | 50 KB     | ######################################################################################################################## | 100% 
intel-openmp-2018.0. | 1004 KB   | ######################################################################################################################## | 100% 
pyzmq-17.1.2         | 407 KB    | ######################################################################################################################## | 100% 
babel-2.6.0          | 5.7 MB    | ######################################################################################################################## | 100% 
python-3.6.6         | 15.4 MB   | ######################################################################################################################## | 100% 
markupsafe-1.0       | 23 KB     | ######################################################################################################################## | 100% 
ipython-6.5.0        | 1.0 MB    | ######################################################################################################################## | 100% 
sphinxcontrib-websup | 36 KB     | ######################################################################################################################## | 100% 
urllib3-1.23         | 152 KB    | ######################################################################################################################## | 100% 
twisted-18.7.0       | 4.9 MB    | ######################################################################################################################## | 100% 
widgetsnbextension-3 | 1.7 MB    | ######################################################################################################################## | 100% 
ncurses-6.1          | 888 KB    | ######################################################################################################################## | 100% 
pip-10.0.1           | 1.8 MB    | ######################################################################################################################## | 100% 
mccabe-0.6.1         | 14 KB     | ######################################################################################################################## | 100% 
scikit-learn-0.19.1  | 4.8 MB    | ######################################################################################################################## | 100% 
mkl_fft-1.0.4        | 137 KB    | ######################################################################################################################## | 100% 
qtconsole-4.4.1      | 156 KB    | ######################################################################################################################## | 100% 
jsonschema-2.6.0     | 62 KB     | ######################################################################################################################## | 100% 
snowballstemmer-1.2. | 85 KB     | ######################################################################################################################## | 100% 
xz-5.2.4             | 269 KB    | ######################################################################################################################## | 100% 
notebook-5.6.0       | 7.4 MB    | ######################################################################################################################## | 100% 
parso-0.3.1          | 114 KB    | ######################################################################################################################## | 100% 
mkl-2018.0.3         | 149.2 MB  | ######################################################################################################################## | 100% 
idna-2.7             | 132 KB    | ######################################################################################################################## | 100% 
bleach-2.1.4         | 33 KB     | ######################################################################################################################## | 100% 
pcre-8.42            | 224 KB    | ######################################################################################################################## | 100% 
cryptography-2.3.1   | 540 KB    | ######################################################################################################################## | 100% 
rope-0.11.0          | 282 KB    | ######################################################################################################################## | 100% 
prometheus_client-0. | 52 KB     | ######################################################################################################################## | 100% 
jinja2-2.10          | 184 KB    | ######################################################################################################################## | 100% 
libsodium-1.0.16     | 324 KB    | ######################################################################################################################## | 100% 
future-0.16.0        | 634 KB    | ######################################################################################################################## | 100% 
chardet-3.0.4        | 189 KB    | ######################################################################################################################## | 100% 
sip-4.19.12          | 253 KB    | ######################################################################################################################## | 100% 
libgfortran-3.0.1    | 495 KB    | ######################################################################################################################## | 100% 
pytest-3.7.3         | 309 KB    | ######################################################################################################################## | 100% 
dbus-1.13.2          | 540 KB    | ######################################################################################################################## | 100% 
numpy-base-1.15.1    | 4.0 MB    | ######################################################################################################################## | 100% 
asn1crypto-0.24.0    | 154 KB    | ######################################################################################################################## | 100% 
ipython_genutils-0.2 | 39 KB     | ######################################################################################################################## | 100% 
psutil-5.4.7         | 314 KB    | ######################################################################################################################## | 100% 
pylint-2.1.1         | 795 KB    | ######################################################################################################################## | 100% 
html5lib-1.0.1       | 184 KB    | ######################################################################################################################## | 100% 
pexpect-4.6.0        | 77 KB     | ######################################################################################################################## | 100% 
hdf5-1.8.18          | 3.6 MB    | ######################################################################################################################## | 100% 
sphinx-1.7.7         | 1.6 MB    | ######################################################################################################################## | 100% 
typed-ast-1.1.0      | 183 KB    | ######################################################################################################################## | 100% 
setuptools-40.2.0    | 554 KB    | ######################################################################################################################## | 100% 
nbformat-4.4.0       | 138 KB    | ######################################################################################################################## | 100% 
jupyter_client-5.2.3 | 124 KB    | ######################################################################################################################## | 100% 
h5py-2.8.0           | 900 KB    | ######################################################################################################################## | 100% 
libpng-1.6.34        | 319 KB    | ######################################################################################################################## | 100% 
more-itertools-4.3.0 | 83 KB     | ######################################################################################################################## | 100% 
traitsui-6.0.0       | 857 KB    | ######################################################################################################################## | 100% 
atomicwrites-1.2.0   | 11 KB     | ######################################################################################################################## | 100% 
pillow-5.1.0         | 542 KB    | ######################################################################################################################## | 100% 
tornado-5.1          | 665 KB    | ######################################################################################################################## | 100% 
requests-2.19.1      | 96 KB     | ######################################################################################################################## | 100% 
pycparser-2.18       | 169 KB    | ######################################################################################################################## | 100% 
docutils-0.14        | 689 KB    | ######################################################################################################################## | 100% 
icu-58.2             | 22.3 MB   | ######################################################################################################################## | 100% 
pyasn1-modules-0.2.2 | 86 KB     | ######################################################################################################################## | 100% 
alabaster-0.7.11     | 16 KB     | ######################################################################################################################## | 100% 
webencodings-0.5.1   | 19 KB     | ######################################################################################################################## | 100% 
pyopenssl-18.0.0     | 82 KB     | ######################################################################################################################## | 100% 
nbconvert-5.3.1      | 405 KB    | ######################################################################################################################## | 100% 
pyface-6.0.0         | 1014 KB   | ######################################################################################################################## | 100% 
hyperlink-18.0.0     | 62 KB     | ######################################################################################################################## | 100% 
pyasn1-0.4.4         | 101 KB    | ######################################################################################################################## | 100% 
ipywidgets-7.4.0     | 150 KB    | ######################################################################################################################## | 100% 
zope-1.0             | 2 KB      | ######################################################################################################################## | 100% 
testpath-0.3.1       | 90 KB     | ######################################################################################################################## | 100% 
libxml2-2.9.8        | 1.9 MB    | ######################################################################################################################## | 100% 
wrapt-1.10.11        | 41 KB     | ######################################################################################################################## | 100% 
pycodestyle-2.3.1    | 55 KB     | ######################################################################################################################## | 100% 
blas-1.0             | 5 KB      | ######################################################################################################################## | 100% 
gettext-0.19.8.1     | 3.4 MB    | ######################################################################################################################## | 100% 
olefile-0.45.1       | 47 KB     | ######################################################################################################################## | 100% 
jpeg-9b              | 236 KB    | ######################################################################################################################## | 100% 
readline-7.0         | 393 KB    | ######################################################################################################################## | 100% 
pytz-2018.5          | 231 KB    | ######################################################################################################################## | 100% 
python.app-2         | 1.3 MB    | ######################################################################################################################## | 100% 
zeromq-4.2.5         | 495 KB    | ######################################################################################################################## | 100% 
qt-5.9.6             | 78.1 MB   | ######################################################################################################################## | 100% 
numpy-1.15.1         | 37 KB     | ######################################################################################################################## | 100% 
sqlite-3.24.0        | 2.2 MB    | ######################################################################################################################## | 100% 
numpydoc-0.8.0       | 42 KB     | ######################################################################################################################## | 100% 
send2trash-1.5.0     | 16 KB     | ######################################################################################################################## | 100% 
flake8-3.5.0         | 121 KB    | ######################################################################################################################## | 100% 
certifi-2018.8.24    | 139 KB    | ######################################################################################################################## | 100% 
py-1.5.4             | 137 KB    | ######################################################################################################################## | 100% 
libtiff-4.0.9        | 544 KB    | ######################################################################################################################## | 100% 
service_identity-17. | 18 KB     | ######################################################################################################################## | 100% 
jupyter-1.0.0        | 5 KB      | ######################################################################################################################## | 100% 
jupyter_console-5.2. | 36 KB     | ######################################################################################################################## | 100% 
zlib-1.2.11          | 101 KB    | ######################################################################################################################## | 100% 
traitlets-4.3.2      | 131 KB    | ######################################################################################################################## | 100% 
constantly-15.1.0    | 13 KB     | ######################################################################################################################## | 100% 
pandas-0.23.4        | 9.3 MB    | ######################################################################################################################## | 100% 
entrypoints-0.2.3    | 9 KB      | ######################################################################################################################## | 100% 
scipy-1.1.0          | 15.4 MB   | ######################################################################################################################## | 100% 
jupyter_core-4.4.0   | 63 KB     | ######################################################################################################################## | 100% 
six-1.11.0           | 21 KB     | ######################################################################################################################## | 100% 
qtawesome-0.4.4      | 159 KB    | ######################################################################################################################## | 100% 
openssl-1.0.2p       | 3.4 MB    | ######################################################################################################################## | 100% 
mkl_random-1.0.1     | 349 KB    | ######################################################################################################################## | 100% 
lazy-object-proxy-1. | 29 KB     | ######################################################################################################################## | 100% 
ipykernel-4.8.2      | 145 KB    | ######################################################################################################################## | 100% 
pyflakes-1.6.0       | 85 KB     | ######################################################################################################################## | 100% 
pandoc-2.2.3.2       | 13.8 MB   | ######################################################################################################################## | 100% 
traits-4.6.0         | 408 KB    | ######################################################################################################################## | 100% 
packaging-17.1       | 33 KB     | ######################################################################################################################## | 100% 
zope.interface-4.5.0 | 198 KB    | ######################################################################################################################## | 100% 
matplotlib-2.2.2     | 6.7 MB    | ######################################################################################################################## | 100% 
jsoncpp-1.8.3        | 169 KB    | ######################################################################################################################## | 100% 
tbb-2018.0.5         | 155 KB    | ######################################################################################################################## | 100% 
pluggy-0.7.1         | 25 KB     | ######################################################################################################################## | 100% 
incremental-17.5.0   | 25 KB     | ######################################################################################################################## | 100% 
pysocks-1.6.8        | 22 KB     | ######################################################################################################################## | 100% 
ca-certificates-2018 | 124 KB    | ######################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting mne (from -r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 1))
Collecting mayavi (from -r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 2))
Collecting PySurfer (from -r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/8a/16/832a4283dd31de0fdb8bc57b7500abd5f1c764871c1bc6150097cfa757bf/pysurfer-0.8.0.tar.gz
Collecting nitime (from -r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 4))
Collecting nibabel (from -r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 5))
Collecting nilearn (from -r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/f5/b8/ecf17d4ce0aee488ea4c1dc483cd191811f79c644010255258623988bd5b/nilearn-0.4.2-py2.py3-none-any.whl
Collecting neo (from -r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 7))
Collecting pytest-sugar (from -r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 8))
Collecting pytest-faulthandler (from -r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/52/d7/13e81ff8f3f9e2ee3d22a59e0d09a4010aaa21b41dd088d757148ccca2be/pytest_faulthandler-1.5.0-py2.py3-none-any.whl
Collecting pydocstyle (from -r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/43/8a/f1141af0c8406788a5c38ad5001d4163d903b5384a6517239d2ac42734c8/pydocstyle-2.1.1-py3-none-any.whl
Collecting codespell (from -r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 11))
Collecting python-picard (from -r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 12))
Requirement already satisfied: pygments in ./anaconda/envs/mne/lib/python3.6/site-packages (from mayavi->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 2)) (2.2.0)
Collecting vtk (from mayavi->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/80/23/39900aa96ceb3f40639849e3678de55b762e11ab4b6261ce75e5798b828d/vtk-8.1.1-cp36-cp36m-macosx_10_6_x86_64.whl
Requirement already satisfied: numpy in ./anaconda/envs/mne/lib/python3.6/site-packages (from mayavi->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 2)) (1.15.1)
Requirement already satisfied: traits>=4.6.0 in ./anaconda/envs/mne/lib/python3.6/site-packages (from mayavi->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 2)) (4.6.0)
Collecting envisage (from mayavi->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ea/2a/7efcd2c44a638a5e3e65e39f7e5bd4cf952ef4ffc71768730cf19fef1e4e/envisage-4.7.0-py3-none-any.whl
Collecting apptools (from mayavi->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 2))
Requirement already satisfied: pyface>=6.0.0 in ./anaconda/envs/mne/lib/python3.6/site-packages (from mayavi->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 2)) (6.0.0)
Requirement already satisfied: traitsui>=6.0.0 in ./anaconda/envs/mne/lib/python3.6/site-packages (from mayavi->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 2)) (6.0.0)
Requirement already satisfied: scipy in ./anaconda/envs/mne/lib/python3.6/site-packages (from nitime->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 4)) (1.1.0)
Requirement already satisfied: matplotlib in ./anaconda/envs/mne/lib/python3.6/site-packages (from nitime->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 4)) (2.2.2)
Collecting quantities>=0.9.0 (from neo->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 7))
Requirement already satisfied: pytest>=2.9 in ./anaconda/envs/mne/lib/python3.6/site-packages (from pytest-sugar->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 8)) (3.7.3)
Collecting termcolor>=1.1.0 (from pytest-sugar->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 8))
Requirement already satisfied: snowballstemmer in ./anaconda/envs/mne/lib/python3.6/site-packages (from pydocstyle->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 10)) (1.2.1)
Requirement already satisfied: six in ./anaconda/envs/mne/lib/python3.6/site-packages (from pydocstyle->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 10)) (1.11.0)
Collecting configobj (from apptools->mayavi->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 2))
Requirement already satisfied: cycler>=0.10 in ./anaconda/envs/mne/lib/python3.6/site-packages (from matplotlib->nitime->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 4)) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./anaconda/envs/mne/lib/python3.6/site-packages (from matplotlib->nitime->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 4)) (2.2.0)
Requirement already satisfied: python-dateutil>=2.1 in ./anaconda/envs/mne/lib/python3.6/site-packages (from matplotlib->nitime->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 4)) (2.7.3)
Requirement already satisfied: pytz in ./anaconda/envs/mne/lib/python3.6/site-packages (from matplotlib->nitime->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 4)) (2018.5)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda/envs/mne/lib/python3.6/site-packages (from matplotlib->nitime->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: py>=1.5.0 in ./anaconda/envs/mne/lib/python3.6/site-packages (from pytest>=2.9->pytest-sugar->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 8)) (1.5.4)
Requirement already satisfied: setuptools in ./anaconda/envs/mne/lib/python3.6/site-packages (from pytest>=2.9->pytest-sugar->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 8)) (40.2.0)
Requirement already satisfied: attrs>=17.4.0 in ./anaconda/envs/mne/lib/python3.6/site-packages (from pytest>=2.9->pytest-sugar->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 8)) (18.1.0)
Requirement already satisfied: more-itertools>=4.0.0 in ./anaconda/envs/mne/lib/python3.6/site-packages (from pytest>=2.9->pytest-sugar->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 8)) (4.3.0)
Requirement already satisfied: atomicwrites>=1.0 in ./anaconda/envs/mne/lib/python3.6/site-packages (from pytest>=2.9->pytest-sugar->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 8)) (1.2.0)
Requirement already satisfied: pluggy>=0.7 in ./anaconda/envs/mne/lib/python3.6/site-packages (from pytest>=2.9->pytest-sugar->-r /Users/zacharystow/condaenv.twEPhB.requirements.txt (line 8)) (0.7.1)
Building wheels for collected packages: PySurfer
  Running setup.py bdist_wheel for PySurfer ... error
  Complete output from command /Users/zacharystow/anaconda/envs/mne/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/gw/xp651r6n7tv0m8hzhf_gkf680000gn/T/pip-install-0by84_ul/PySurfer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/gw/xp651r6n7tv0m8hzhf_gkf680000gn/T/pip-wheel-m7o4y3x5 --python-tag cp36:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/gw/xp651r6n7tv0m8hzhf_gkf680000gn/T/pip-install-0by84_ul/PySurfer/setup.py", line 64, in <module>
      check_dependencies()
    File "/private/var/folders/gw/xp651r6n7tv0m8hzhf_gkf680000gn/T/pip-install-0by84_ul/PySurfer/setup.py", line 51, in check_dependencies
      raise ImportError("Missing dependencies: %s" % missing)
  ImportError: Missing dependencies: mayavi
  
  ----------------------------------------
  Failed building wheel for PySurfer
  Running setup.py clean for PySurfer
Failed to build PySurfer
twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
Installing collected packages: mne, vtk, configobj, apptools, envisage, mayavi, nibabel, PySurfer, nitime, nilearn, quantities, neo, termcolor, pytest-sugar, pytest-faulthandler, pydocstyle, codespell, python-picard
  Running setup.py install for PySurfer ... done
Successfully installed PySurfer-0.8.0 apptools-4.4.0 codespell-1.13.0 configobj-5.0.6 envisage-4.7.0 mayavi-4.6.1 mne-0.16.2 neo-0.6.1 nibabel-2.3.0 nilearn-0.4.2 nitime-0.7 pydocstyle-2.1.1 pytest-faulthandler-1.5.0 pytest-sugar-0.9.1 python-picard-0.3 quantities-0.12.2 termcolor-1.1.0 vtk-8.1.1
#
# To activate this environment, use:
# > source activate mne
#
# To deactivate an active environment, use:
# > source deactivate
#

Zacharys-MacBook-Pro:~ zacharystow$ source activate mne
(Canopy 64bit) Zacharys-MacBook-Pro:~ zacharystow$
```
I installed PyHamcrest and mayavi using:
```
conda install -c conda-forge pyhamcrest 
conda install -c anaconda mayavi 
```
Yet, I still get the same error and don't know why that doesn't fix the problem. 
Would should I do?

**Comment by agramfort** [comment]
I can read that PySurfer and mayavi were successfully installed

Successfully installed PySurfer-0.8.0 apptools-4.4.0 codespell-1.13.0
configobj-5.0.6 envisage-4.7.0 mayavi-4.6.1 ...

did you try to run these libraries after the installation?

**Comment by zachs321** [comment]
Yah I ran 
`source activate mne`
to activate the environment. Then I opened the anaconda python prompt and ran
`>>> import mne`
and get
`ImportError: No module named mne`

**Comment by agramfort** [comment]
can you delete the mne env, do it again and paste the full trace back with
the command you typed?

**Comment by zachs321** [comment]
Ok, I just edited the first comment and pasted everything.

**Comment by agramfort** [comment]
It seems to install mayavi but then pysurfer tries to import it and it fails so it tells you that mayavi is missing. Can you try to "import mayavi" and see if you get errors from this environment?

**Comment by zachs321** [comment]
This is what I get:
```
(Canopy 64bit) Zacharys-MacBook-Pro:~ zacharystow$ python3
  Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) 
  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import mayavi
  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ModuleNotFoundError: No module named 'mayavi'
  >>> 
  [3]+  Stopped                 python3
  (Canopy 64bit) Zacharys-MacBook-Pro:~ zacharystow$ python
  Enthought Canopy Python 2.7.11 | 64-bit | (default, Jun 11 2016, 03:41:56) 
  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import mayavi
  >>> 
  [4]+  Stopped                 python
  (Canopy 64bit) Zacharys-MacBook-Pro:~ zacharystow$
```

**Comment by agramfort** [comment]
you seem to have a mix of anaconda and canopy on your system.
this can explain the issues you have.

I would make sure Canopy and anaconda don't interact badly and
eventually reinstall them from scratch after properly removing them.

**Comment by larsoner** [comment]
This should now be fixed with latest PySurfer release but let us know if it is not!
