### ISSUE TITLE
regression in plot_sleep.py due to #5841

### ISSUE THREAD

**Issue by massich** [mne-tools/mne-python#5864]
Circle CI is red. I've no idea why was not red in #5841.

```sh
~/code/mne-python master*
(mne) ❯ python tutorials/plot_sleep.py   
/home/sik/miniconda3/envs/mne/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "tutorials/plot_sleep.py", line 90, in <module>
    raw_train.plot(duration=60, scalings='auto')
  File "/home/sik/code/mne-python/mne/io/base.py", line 1873, in plot
    event_id=event_id)
  File "/home/sik/code/mne-python/mne/viz/raw.py", line 265, in plot_raw
    scalings = _compute_scalings(scalings, raw)
  File "/home/sik/code/mne-python/mne/viz/utils.py", line 1634, in _compute_scalings
    data = inst._read_segment(tmin, tmax)
  File "/home/sik/code/mne-python/mne/io/base.py", line 561, in _read_segment
    cals, mult)
  File "<string>", line 2, in _read_segment_file
  File "/home/sik/code/mne-python/mne/utils.py", line 953, in verbose
    return function(*args, **kwargs)
  File "/home/sik/code/mne-python/mne/io/edf/edf.py", line 284, in _read_segment_file
    if ci in stim_channel:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by massich** [comment]
I did not see that @larsoner catch it just 1h ago https://github.com/mne-tools/mne-python/pull/5841#issuecomment-457190398
