### ISSUE TITLE
interactivity in epochs.plot_topo_image requires plt.ion()

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#6101]
It appears that the "click to magnify this channel" interactivity only works if the user has already imported pyplot and called `plt.ion()`. Try this in a fresh ipython session:

```
import os
import mne
sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file, verbose=False)
events = mne.find_events(raw, stim_channel='STI 014')
epochs = mne.Epochs(raw, events)
epochs.plot_topo_image()
# now click on any channel's imagemap, nothing happens
# now close the plot window, and...
import matplotlib.pyplot as plt
plt.show()  # only now does the enlarged image appear
```

Of course, if the last two steps aren't performed, then those orphaned figures hang around and only show up when the *next* MNE-Python plotting call is executed.  Would it work to use `matplotlib.is_interactive()` to get the ion/ioff state before the plot call, and if necessary turn it on for the duration of the plot, and then turn it back off again?

**Comment by larsoner** [comment]
> Would it work to use matplotlib.is_interactive() to get the ion/ioff state before the plot call, and if necessary turn it on for the duration of the plot, and then turn it back off again?

It's probably not safe to mess with the `ion` / `ioff` state, it means that users can unexpectedly have code execute that they did not want to.

There is probably a way to get the newly spawned figures to appear. It's possible we need to call `plt.show()` after creating any new figures. It seems like something like that should work.

In a worst case, if we can't find a way to get the new ones to show up without messing with interactive state, we can emit a warning when the user clicks that the figure cannot be shown due to `ioff()`.

**Comment by drammock** [comment]
right, of course. calling `plt.show()` is a cleaner solution.

**Comment by drammock** [comment]
Turns out this problem is worse with `raw.plot_psd_topo()`:

```
(mnedev) [~] $ ipython
In [1]: import os 
   ...: import mne 
   ...: sample_data_folder = mne.datasets.sample.data_path() 
   ...: sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample', 
   ...:                                     'sample_audvis_raw.fif') 
   ...: raw = mne.io.read_raw_fif(sample_data_raw_file, verbose=False) 
   ...: raw.plot_psd_topo()                                                                                                           
Effective window size : 3.410 (s)
Out[1]: <Figure size 640x480 with 1 Axes>
can only concatenate list (not "NoneType") to list
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/opt/mne-python/mne/viz/topo.py", line 259, in _plot_topo_onpick
    show_func(ax, ch_idx)
  File "/opt/mne-python/mne/viz/topo.py", line 420, in _plot_timeseries
    _setup_ax_spines(ax, vline, tmin, tmax)
  File "/opt/mne-python/mne/viz/utils.py", line 2335, in _setup_ax_spines
    xticks = sorted(list(set([x for x in axes.get_xticks()] + vlines)))
TypeError: can only concatenate list (not "NoneType") to list
In [2]: # closed window at this point, then:                                                                                          
In [3]: import matplotlib.pyplot as plt                                                                                               
In [4]: plt.show()                                                                                                                    
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2679, in mouse_move
    s = event.inaxes.format_coord(event.xdata, event.ydata)
  File "/opt/mne-python/mne/viz/topo.py", line 389, in <lambda>
    ax.format_coord = lambda x, y: _format_coord(x, y, labels=labels, ax=ax)
  File "/opt/mne-python/mne/viz/topo.py", line 369, in _format_coord
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
  File "/opt/mne-python/mne/viz/topo.py", line 369, in <listcomp>
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2679, in mouse_move
    s = event.inaxes.format_coord(event.xdata, event.ydata)
  File "/opt/mne-python/mne/viz/topo.py", line 389, in <lambda>
    ax.format_coord = lambda x, y: _format_coord(x, y, labels=labels, ax=ax)
  File "/opt/mne-python/mne/viz/topo.py", line 369, in _format_coord
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
  File "/opt/mne-python/mne/viz/topo.py", line 369, in <listcomp>
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2679, in mouse_move
    s = event.inaxes.format_coord(event.xdata, event.ydata)
  File "/opt/mne-python/mne/viz/topo.py", line 389, in <lambda>
    ax.format_coord = lambda x, y: _format_coord(x, y, labels=labels, ax=ax)
  File "/opt/mne-python/mne/viz/topo.py", line 369, in _format_coord
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
  File "/opt/mne-python/mne/viz/topo.py", line 369, in <listcomp>
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2679, in mouse_move
    s = event.inaxes.format_coord(event.xdata, event.ydata)
  File "/opt/mne-python/mne/viz/topo.py", line 389, in <lambda>
    ax.format_coord = lambda x, y: _format_coord(x, y, labels=labels, ax=ax)
  File "/opt/mne-python/mne/viz/topo.py", line 369, in _format_coord
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
  File "/opt/mne-python/mne/viz/topo.py", line 369, in <listcomp>
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2679, in mouse_move
    s = event.inaxes.format_coord(event.xdata, event.ydata)
  File "/opt/mne-python/mne/viz/topo.py", line 389, in <lambda>
    ax.format_coord = lambda x, y: _format_coord(x, y, labels=labels, ax=ax)
  File "/opt/mne-python/mne/viz/topo.py", line 369, in _format_coord
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
  File "/opt/mne-python/mne/viz/topo.py", line 369, in <listcomp>
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2679, in mouse_move
    s = event.inaxes.format_coord(event.xdata, event.ydata)
  File "/opt/mne-python/mne/viz/topo.py", line 389, in <lambda>
    ax.format_coord = lambda x, y: _format_coord(x, y, labels=labels, ax=ax)
  File "/opt/mne-python/mne/viz/topo.py", line 369, in _format_coord
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
  File "/opt/mne-python/mne/viz/topo.py", line 369, in <listcomp>
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2679, in mouse_move
    s = event.inaxes.format_coord(event.xdata, event.ydata)
  File "/opt/mne-python/mne/viz/topo.py", line 389, in <lambda>
    ax.format_coord = lambda x, y: _format_coord(x, y, labels=labels, ax=ax)
  File "/opt/mne-python/mne/viz/topo.py", line 369, in _format_coord
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
  File "/opt/mne-python/mne/viz/topo.py", line 369, in <listcomp>
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2679, in mouse_move
    s = event.inaxes.format_coord(event.xdata, event.ydata)
  File "/opt/mne-python/mne/viz/topo.py", line 389, in <lambda>
    ax.format_coord = lambda x, y: _format_coord(x, y, labels=labels, ax=ax)
  File "/opt/mne-python/mne/viz/topo.py", line 369, in _format_coord
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
  File "/opt/mne-python/mne/viz/topo.py", line 369, in <listcomp>
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2679, in mouse_move
    s = event.inaxes.format_coord(event.xdata, event.ydata)
  File "/opt/mne-python/mne/viz/topo.py", line 389, in <lambda>
    ax.format_coord = lambda x, y: _format_coord(x, y, labels=labels, ax=ax)
  File "/opt/mne-python/mne/viz/topo.py", line 369, in _format_coord
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
  File "/opt/mne-python/mne/viz/topo.py", line 369, in <listcomp>
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2679, in mouse_move
    s = event.inaxes.format_coord(event.xdata, event.ydata)
  File "/opt/mne-python/mne/viz/topo.py", line 389, in <lambda>
    ax.format_coord = lambda x, y: _format_coord(x, y, labels=labels, ax=ax)
  File "/opt/mne-python/mne/viz/topo.py", line 369, in _format_coord
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
  File "/opt/mne-python/mne/viz/topo.py", line 369, in <listcomp>
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/opt/miniconda3/envs/mnedev/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2679, in mouse_move
    s = event.inaxes.format_coord(event.xdata, event.ydata)
  File "/opt/mne-python/mne/viz/topo.py", line 389, in <lambda>
    ax.format_coord = lambda x, y: _format_coord(x, y, labels=labels, ax=ax)
  File "/opt/mne-python/mne/viz/topo.py", line 369, in _format_coord
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
  File "/opt/mne-python/mne/viz/topo.py", line 369, in <listcomp>
    nearby_data = [(data[n], labels[n], times[n]) for n in nearby]
TypeError: 'NoneType' object is not subscriptable
In [5]: # this second traceback vomit was simply from mousing over the plot area,
In [6]: # and appears to be a separate issue; it happens even if plt.ion() is called 
In [7]: # before the call to raw.plot_psd_topo()
```

**Comment by larsoner** [comment]
Looks like there are indeed a few bugs, can you see if the fix isn't too bad? Or let me know if you'd rather have me look

**Comment by drammock** [comment]
You can assign it to me, I'll look on Monday.
