### ISSUE TITLE
RuntimeError: Zip file did not have correct names` when downloading fsaverage on windows

### ISSUE THREAD

**Issue by mmagnuski** [mne-tools/mne-python#6292]
I get `RuntimeError: Zip file did not have correct names` when downloading fsaverage files on Windows machine:
```python
from mne.datasets import fetch_fsaverage
fs_dir = fetch_fsaverage(verbose=True)
```

```python-traceback
179 files missing from c:\src\mne-python\mne\datasets\_fsaverage\root.txt in C:\Users\mmagn\mne_data\MNE-fsaverage-data
Downloading missing files remotely
Downloading https://files.osf.io/v1/resources/rxvq7/providers/osfstorage/5cbdba4ef2be3c0019091890?action=download&version=2&direct&revision=2 (186.7 MB)
[........................................] 100.00% (186.7 MB,  25.5 MB/s) \   
Verifying hash 5133fe92b7b8f03ae19219d5f46e4177.
File saved as C:\Users\mmagn\AppData\Local\Temp\tmpof0geus7\temp.zip.

Extracting missing files
Traceback (most recent call last):

  File "<ipython-input-47-9a322ebca572>", line 2, in <module>
    fs_dir = fetch_fsaverage(verbose=True)

  File "<c:\src\mne-python\mne\externals\decorator.py:decorator-gen-331>", line 2, in fetch_fsaverage

  File "c:\src\mne-python\mne\utils\_logging.py", line 88, in wrapper
    return function(*args, **kwargs)

  File "c:\src\mne-python\mne\datasets\_fsaverage\base.py", line 92, in fetch_fsaverage
    hash_=data['hash_'],

  File "c:\src\mne-python\mne\datasets\utils.py", line 798, in _manifest_check_download
    '\n%s' % ('\n'.join(missing)))

RuntimeError: Zip file did not have correct names:
fsaverage/
fsaverage/bem/
fsaverage/label/
fsaverage/mri.2mm/
fsaverage/mri/
fsaverage/mri/orig/
fsaverage/mri/transforms/
fsaverage/mri/transforms/bak/
fsaverage/scripts/
fsaverage/src/
fsaverage/stats/
fsaverage/surf/
fsaverage/tmp/
fsaverage/touch/
fsaverage/trash/
```

**Comment by larsoner** [comment]
Can you change line 794 to say `if not f.endswith('/')` instead of `if not f.endswithe(op.sep)` and see if it fixes it? I think I made a faulty assumption about how `members` would work on Windows.
