### ISSUE TITLE
ENH: concatenate_epochs can be more memory efficient

### ISSUE THREAD

**Issue by WilliamLabCea** [mne-tools/mne-python#6758]
Hello,

I was trying to concatenate 2 epochs with mne.concatenate_epochs, but python return memory error related to numpy array.

Last_epochs_standard = mne.concatenate_epochs([epochs1,epochs2])
Loading data for 33684 events and 1688 original time points ...
Loading data for 47154 events and 1688 original time points ...
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/wvxxxx/anaconda3/envs/Nex/lib/python3.7/site-packages/mne/epochs.py", line 2723, in concatenate_epochs
    add_offset=add_offset))
  File "/home/wvxxxx/anaconda3/envs/Nex/lib/python3.7/site-packages/mne/epochs.py", line 2683, in _concatenate_epochs
    data = np.concatenate(data, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
MemoryError: Unable to allocate array with shape (80838, 32, 1688) and data type float64

 The data size is the problem with mne.concatenate. Does it have another way to proceed ?

Best.

William

**Comment by larsoner** [comment]
@WilliamLabCea #8185 should hopefully fix this
