### ISSUE TITLE
raw plot error

### ISSUE THREAD

**Issue by MadsJensen** [mne-tools/mne-python#694]
Hi, I got teh following error when trying to use raw.plot on a raw fiff file from a neuromag Triux system, 

```
raw = mne.fiff.Raw('sub_2_plan_tsss_mc.fif', preload = True)
Opening raw data file /media/mje/KINGSTON/MEG_libet/Data/sub_2_plan_tsss_mc.fif...
Current compensation grade : 0
    Range : 110000 ... 583999 =    110.000 ...   583.999 secs
Ready.
Reading 0 ... 473999  =      0.000 ...   473.999 secs...
[done]

raw.plot()
Traceback (most recent call last):

  File "<ipython-input-46-d4ffb847f525>", line 1, in <module>
    raw.plot()

  File "/home/mje/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/mne-0.7.git-py2.7.egg/mne/fiff/raw.py", line 1054, in plot
    order, show_options, title, show)

  File "/home/mje/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/mne-0.7.git-py2.7.egg/mne/viz.py", line 2537, in plot_raw
    raise RuntimeError('Some channels not classified, please report '

RuntimeError: Some channels not classified, please report this problem

```

Sorry if this has been posted before, but I could not find it. 

best,
mads

**Comment by wenzn** [comment]
I met this problem once, just for I changed the API's pick.py file pick_types(info, meg=True, eeg=False...),
since I just use eeg, so I changed it to pick_types(info, meg=False, eeg=True...), but it seemd to be harmful to the API, so I just back it
