### ISSUE TITLE
pytest-sugar is not working with pytest v5.4.0 (released on March 12th 2020)

### ISSUE THREAD

**Issue by GuillaumeFavelier** [mne-tools/mne-python#7437]
[Travis fails](
https://travis-ci.org/github/mne-tools/mne-python/jobs/661562630?utm_medium=notification&utm_source=github_status) because of compatibility issues with pytest 5.4.0:

<details>

```
Coverage.py warning: --include is ignored because --source is set (include-ignored)

INTERNALERROR> Traceback (most recent call last):

INTERNALERROR>   File "/home/travis/miniconda/lib/python3.7/site-packages/_pytest/main.py", line 187, in wrap_session

INTERNALERROR>     config._do_configure()

INTERNALERROR>   File "/home/travis/miniconda/lib/python3.7/site-packages/_pytest/config/__init__.py", line 820, in _do_configure

INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))

INTERNALERROR>   File "/home/travis/miniconda/lib/python3.7/site-packages/pluggy/hooks.py", line 308, in call_historic

INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)

INTERNALERROR>   File "/home/travis/miniconda/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec

INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)

INTERNALERROR>   File "/home/travis/miniconda/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>

INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,

INTERNALERROR>   File "/home/travis/miniconda/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall

INTERNALERROR>     return outcome.get_result()

INTERNALERROR>   File "/home/travis/miniconda/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result

INTERNALERROR>     raise ex[1].with_traceback(ex[2])

INTERNALERROR>   File "/home/travis/miniconda/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall

INTERNALERROR>     res = hook_impl.function(*args)

INTERNALERROR>   File "/home/travis/miniconda/lib/python3.7/site-packages/pytest_sugar.py", line 176, in pytest_configure

INTERNALERROR>     sugar_reporter = SugarTerminalReporter(standard_reporter)

INTERNALERROR>   File "/home/travis/miniconda/lib/python3.7/site-packages/pytest_sugar.py", line 214, in __init__

INTERNALERROR>     self.writer = self._tw

INTERNALERROR> AttributeError: can't set attribute

The command "pytest -m "${CONDITION}" --tb=short --cov=mne ${USE_DIRS}" exited with 3.
```

</details>

![image](https://user-images.githubusercontent.com/18143289/76571347-9633ee80-64b7-11ea-9e87-1e16591a5f41.png)

This happened in https://github.com/mne-tools/mne-python/pull/7294 and https://github.com/mne-tools/mne-python/pull/7435 and has been reported on [pytest-sugar](https://github.com/Teemu/pytest-sugar/issues/187) already. Do we have a way to mitigate, maybe downgrade `pytest`?

**Comment by larsoner** [comment]
Yes just add a != to whatever the problematic version is for now
