### ISSUE TITLE
BUG: Cant read elp with read_custom_montage

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-python#7585]
```
import os.path as op
import mne
fname = op.join(op.dirname(mne.__file__), 'io', 'kit', 'tests', 'data', 'test.elp')
mne.channels.read_custom_montage(fname)
```
gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/larsoner/python/mne-python/mne/channels/montage.py", line 988, in read_custom_montage
    montage = _read_elp_besa(fname, head_size)
  File "/home/larsoner/python/mne-python/mne/channels/_standard_montage_utils.py", line 273, in _read_elp_besa
    data = np.loadtxt(fname, dtype=dtype, skiprows=1)
  File "/home/larsoner/python/numpy/numpy/lib/npyio.py", line 1128, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/home/larsoner/python/numpy/numpy/lib/npyio.py", line 1059, in read_data
    items = pack_items(items, packing)
  File "/home/larsoner/python/numpy/numpy/core/_internal.py", line 873, in __call__
    return self.func(self, *args, **kwargs)
  File "/home/larsoner/python/numpy/numpy/lib/npyio.py", line 1013, in pack_items
    ret.append(self(items[start:start+length], subpacking))
  File "/home/larsoner/python/numpy/numpy/core/_internal.py", line 873, in __call__
    return self.func(self, *args, **kwargs)
  File "/home/larsoner/python/numpy/numpy/lib/npyio.py", line 1004, in pack_items
    return items[0]
IndexError: list index out of range
```
However, this is a file from the `io/kit` module (and it gets used there), so it clearly should be readable. It looks like `mne._digitization._read_dig_points` is what the KIT code uses to read it, it's unclear why we don't or can't use this in `read_custom_montage`.

**Comment by larsoner** [comment]
This works:
```
mne.channels.read_dig_polhemus_isotrak(fname)
```
Perhaps we should try to detect which type of file we have and warn if it's not BESA ELP?

**Comment by agramfort** [comment]
+1

>

**Comment by larsoner** [comment]
Closing in favor of  #7591
