### ISSUE TITLE
Error related to test_config_linux while trying to build documentation locally on Mac

### ISSUE THREAD

**Issue by danieltomasz** [mne-tools/mne-python#8302]
While trying to build the documentation locally I got following error
MNE 21.0
Python 3.8.5 
MacOS Catalina 
I installed requirements
   from here https://github.com/mne-tools/mne-python/blob/bab6cb31f59341c3cf02cfe6f96d10e9adcf52cc/requirements_doc.txt
```
generating gallery for auto_examples/preprocessing... [100%] plot_xdawn_denoising.py
WARNING: /Users/daniel/Downloads/mne-python-master/examples/visualization/plot_meg_sensors.py failed to execute correctly: Traceback (most recent call last):
  File "/Users/daniel/Downloads/mne-python-master/examples/visualization/plot_meg_sensors.py", line 31, in <module>
    'Magnes 3600wh': read_raw_bti(op.join(bti_path, 'test_pdf_linux'),
  File "<decorator-gen-175>", line 21, in read_raw_bti
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/mne/io/bti/bti.py", line 1281, in read_raw_bti
    return RawBTi(pdf_fname, config_fname=config_fname,
  File "<decorator-gen-174>", line 21, in __init__
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/mne/io/bti/bti.py", line 947, in __init__
    info, bti_info = _get_bti_info(
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/mne/io/bti/bti.py", line 1054, in _get_bti_info
    raise ValueError('Could not find the config file %s. Please check'
ValueError: Could not find the config file /Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/mne/io/bti/tests/data/test_config_linux. Please check whether you are in the right directory or pass the full name

generating gallery for auto_examples/visualization... [ 57%] plot_mne_helmet.py
Traceback (most recent call last):
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sphinx_gallery/gen_gallery.py", line 436, in generate_gallery_rst
    generate_dir_rst(src_dir, target_dir, gallery_conf,
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 361, in generate_dir_rst
    intro, title, cost = generate_file_rst(
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 835, in generate_file_rst
    output_blocks, time_elapsed = execute_script(script_blocks,
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 743, in execute_script
    memory_start, _ = gallery_conf['call_memory'](lambda: None)
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sphinx_gallery/gen_gallery.py", line 174, in call_memory
    mem, out = memory_usage(func, max_usage=True, retval=True,
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/memory_profiler.py", line 337, in memory_usage
    p.start()
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 40, in _launch
    tracker_fd = resource_tracker.getfd()
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/resource_tracker.py", line 67, in getfd
    self.ensure_running()
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/resource_tracker.py", line 96, in ensure_running
    warnings.warn('resource_tracker: process died unexpectedly, '
UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sphinx/application.py", line 277, in __init__
    self._init_builder()
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sphinx/application.py", line 333, in _init_builder
    self.events.emit('builder-inited')
  File "/Users/daniel/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sphinx/events.py", line 117, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function generate_gallery_rst at 0x13a2e70d0> for event 'builder-inited' threw an exception

Extension error:
Handler <function generate_gallery_rst at 0x13a2e70d0> for event 'builder-inited' threw an exception
make: *** [dashdoc] Error 2
```

**Comment by agramfort** [comment]
what command did you type in the terminal?

>

**Comment by danieltomasz** [comment]
`make html_stable`

**Comment by agramfort** [comment]
you run this from the doc folder?

>

**Comment by danieltomasz** [comment]
Yes, everything was running almost smoothly till this moment 
(apart from one script from preprocessing folder which hangs on downloading one of the brainstorm datasets, but I solved this manually by running the same script manually, which downloaded this dataset)

**Comment by agramfort** [comment]
ok I think I understand. The file test_config_linux is a data file that we
don't include in the source distribution and that
is not installed. Can you try to install mne with

cd mne-python
pip install -e .

**Comment by danieltomasz** [comment]
After  local mne install, It didn't crash at this point, albeit the execution of the code seems stuck at this point ( 'generating gallery for auto_examples/visualization... [ 52%] plot_meg_sensors.py') more than 5min now

**Comment by agramfort** [comment]
FYI building the entire doc is close to 2h ... :-/

>

**Comment by danieltomasz** [comment]
EDIT: after over  10min it breaks through!  Thanks for your help, I am closing this issue!

**Comment by agramfort** [comment]
it breaks?

>

**Comment by danieltomasz** [comment]
No, it's good :) It finished generating the problematic script and start another one, thanks for the help again!
