### ISSUE TITLE
BUG: parse_folder() with n_jobs>1 for mne.Report causes attribute-error

### ISSUE THREAD

**Issue by marsipu** [mne-tools/mne-python#9101]
#### Describe the bug
When changing the n_jobs-parameter for the parse_folder-method of mne.Report to a value greater than 1, an error is thrown.

#### Steps to reproduce
```python
import mne

path = mne.datasets.sample.data_path(verbose=False)
report = mne.Report(verbose=True)
report.parse_folder(path, pattern='*raw.fif', render_bem=False, n_jobs=2)
report.save('test.html', overwrite=True)
```

#### Expected results
No error.

#### Actual results
```python
Traceback (most recent call last):
  File "<decorator-gen-368>", line 22, in parse_folder
  File "C:\Users\marti\PycharmProjects\mne-python\mne\report.py", line 1620, in parse_folder
    r = parallel(p_fun(self, fname, info, cov, baseline, sfreq, on_error,
  File "C:\Users\marti\PycharmProjects\mne-python\mne\parallel.py", line 128, in run
    return fun(*args, **kwargs)
  File "C:\Users\marti\anaconda3\envs\mnedev\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\Users\marti\anaconda3\envs\mnedev\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\marti\anaconda3\envs\mnedev\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\marti\anaconda3\envs\mnedev\lib\concurrent\futures\_base.py", line 440, in result
    return self.__get_result()
  File "C:\Users\marti\anaconda3\envs\mnedev\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
AttributeError: 'Report' object has no attribute 'projs'
```

#### Additional information
The error seems to be coming from line 362 in report.py. The report-object doesn't have the _projs_-attribute as if somehow lost attributes when being passed to the new process in __iterate_files_ (line 1620). Other attributes as _data_path_ and _title_ seem to survive.

**Comment by hoechenberger** [comment]
I can reproduce this locally, but so far I'm not sure where this is coming from … :(

**Comment by marsipu** [comment]
Guillaume and I found a workaround by adding `prefer='threads'` to parallel_func in l. 1619 of report.py.
But this still doesn't explain the disappearing attribute (and threading shouldn't give much of a perfomance boost)
