### ISSUE TITLE
RuntimeError: main thread is not in main loop when add_figs_to_section  for figs produce using Parallel module

### ISSUE THREAD

**Issue by balandongiv** [mne-tools/mne-python#9506]
#### Describe the bug
Adding list of figures to mne-report section produced `RuntimeError: main thread is not in main loop` . This occur when module 'Parallel` was used. But, no syntax error was generated for a list of figures produced using the conventional for-loop or list comprehension.

For example,

This line work perfectly fine for all the time (`list comprehension`)

`all_fig = [drop_plot ( drop_idx ) for drop_idx in epochs_drop_idx]`

This line may produce the aforementioned error (`parallel`)

`all_fig = Parallel ( n_jobs=-1 ) ( delayed ( self.drop_plot ) ( drop_idx ) for drop_idx in self.epochs_drop_idx )`

Feed the `all_fig` from the `parallel` to `rep.add_figs_to_section ( all_fig, captions=captions )` will result in the compiler return the following syntax error

> Embedding : jquery.js
> Embedding : jquery-ui.min.js
> Embedding : bootstrap.min.js
> Embedding : jquery-ui.min.css
> Embedding : bootstrap.min.css
> Traceback (most recent call last):
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3032, in _wait_cursor_for_draw_cm
>     self.set_cursor(cursors.WAIT)
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 585, in set_cursor
>     window.configure(cursor=cursord[cursor])
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/tkinter/__init__.py", line 1485, in configure
>     return self._configure('configure', cnf, kw)
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/tkinter/__init__.py", line 1476, in _configure
>     self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
> RuntimeError: main thread is not in main loop
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/author/PycharmProjects/project_name/src_code/main.py", line 29, in <module>
>     pp3e( list_subject=xfname )
>   File "/home/author/PycharmProjects/project_name/src_code/pprocessing.py", line 89, in step_3e_able_one_ic_at_a_time
>     qc.zeroed_all_no ()
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/author_tool/qc_ICA.py", line 151, in zeroed_all_no
>     self.iterate_each_component ()
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/author_tool/qc_ICA.py", line 182, in iterate_each_component
>     rep.add_figs_to_section ( fig, captions=captions, section='Pre_ica' )
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/mne/report.py", line 1207, in add_figs_to_section
>     img = _fig_to_img(fig, image_format, scale, auto_close)
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/mne/report.py", line 110, in _fig_to_img
>     bbox_to_inches='tight')
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/matplotlib/figure.py", line 3005, in savefig
>     self.canvas.print_figure(fname, **kwargs)
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2261, in print_figure
>     **kwargs)
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1669, in wrapper
>     return func(*args, **kwargs)
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 508, in print_png
>     FigureCanvasAgg.draw(self)
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 405, in draw
>     else nullcontext()):
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/contextlib.py", line 112, in __enter__
>     return next(self.gen)
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 3035, in _wait_cursor_for_draw_cm
>     self.set_cursor(self._lastCursor)
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 585, in set_cursor
>     window.configure(cursor=cursord[cursor])
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/tkinter/__init__.py", line 1485, in configure
>     return self._configure('configure', cnf, kw)
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/tkinter/__init__.py", line 1476, in _configure
>     self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
> RuntimeError: main thread is not in main loop
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/matplotlib/_pylab_helpers.py", line 86, in destroy_all
>     manager.destroy()
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 482, in destroy
>     self.window.after_idle(self.window.after, 0, delayed_destroy)
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/tkinter/__init__.py", line 764, in after_idle
>     return self.after('idle', func, *args)
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/tkinter/__init__.py", line 756, in after
>     name = self._register(callit)
>   File "/home/author/anaconda3/envs/project_name/lib/python3.7/tkinter/__init__.py", line 1372, in _register
>     self.tk.createcommand(name, f)
> RuntimeError: main thread is not in main loop
> 
> Process finished with exit code 1
> 

#### Steps to reproduce
The structure of the code that produced the above error is similar to the snippet below. Effort has been made to make the snippet as close as possible to the original code that produced the error. However, it should be note that, the snippet below does not produce the aforementioned error. Hence, I found it very difficult to rule out whether this is really mne related problem or not. But, the runtime error trail indicate that there is function call from mne-report in between the error.

```
import mne
from autoreject import Ransac, get_rejection_threshold  # noqa
import numpy as np
from mne.report import Report
from joblib import Parallel, delayed


class manually_qc_data:
    def __init__ (self):
        x = 1
        self.step ()

    def step (self):
        self.ica = mne.preprocessing.read_ica ( 'fit_ica.fif', verbose=None )
        self.epochs = mne.read_epochs ( 'raw-epo.fif', preload=True )

        self.epochs.pick ( 'eeg' )
        reject = get_rejection_threshold ( self.epochs, cv=10, decim=11 )
        self.epochs.drop_bad ( reject=reject, flat=None )

        # make groups of good epoch indices of size 10
        self.epo_selection = self.epochs.selection.tolist ()
        chunk_size = 10
        epochs_chunks = list ( self.epo_selection [i:i + chunk_size]
                               for i in range ( 0, len ( self.epo_selection ), chunk_size ) )

        self.epochs_drop_idx = [list ( set ( self.epo_selection ) - set ( a ) ) for a in epochs_chunks]
        self.make_process ()

    def make_process (self):
        recons_epochs = self.epochs.copy ()
        self.ica.exclude = [1,2,3,4,5]
        self.ica.apply ( recons_epochs )

        # all_fig = [drop_plot ( drop_idx ) for drop_idx in epochs_drop_idx]

        all_fig = Parallel ( n_jobs=-1 ) ( delayed ( self.drop_plot ) ( drop_idx ) for drop_idx in self.epochs_drop_idx )

        rep = Report ()
        captions = ['IC_' + str ( i ) for i in list ( range ( 0, len ( all_fig ) ) )]
        rep.add_figs_to_section ( all_fig, captions=captions )
        rep.save ( 'report.html', overwrite=True, open_browser=False )
        x = 1

    def drop_plot (self, drop_epoch_group):
        fig_ = self.epochs.copy ().drop ( np.in1d ( self.epo_selection, drop_epoch_group ) ).plot ( show=False )
        return fig_


manually_qc_data ()
```

Should this is not a mne related bug, kindly close this issue.

#### Additional information
mne: '0.24.dev0'

**Comment by balandongiv** [comment]
The culprit is `matplotlib.use ( 'TkAgg' )`.

Disabling/commented  `matplotlib.use ( 'TkAgg' )` resolve the issue
