### ISSUE TITLE
Brain.screenshot() fails if mode='rgba' and time_viewer=True

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-python#9562]
MWE:
```python
# %%
from pathlib import Path
import mne
from mne.datasets import sample

mne.viz.set_3d_backend('pyvista')

subject = 'sample'
data_path = Path(sample.data_path())
meg_path = data_path / 'MEG' / subject
subjects_dir = data_path / 'subjects'
stc_path = meg_path / f'{subject}_audvis-meg'

stc = mne.read_source_estimate(stc_path)
brain = stc.plot(subject=subject, subjects_dir=subjects_dir)
screenshot = brain.screenshot(time_viewer=True, mode='rgba')
```

Output:
```
Using pyvista 3d backend.

Using control points [ 5.01632618  6.06303297 21.63565434]
qt.qpa.drawing: Layer-backing can not be explicitly controlled on 10.14 when built against the 10.14 SDK
Traceback (most recent call last):
  File "/private/tmp/foo.py", line 17, in <module>
    screenshot = brain.screenshot(time_viewer=True, mode='rgba')
  File "/Users/hoechenberger/Development/mne-python/mne/viz/_brain/_brain.py", line 2684, in screenshot
    img = concatenate_images([img, trace_img], bgcolor=bgcolor)
  File "/Users/hoechenberger/Development/mne-python/mne/viz/utils.py", line 2347, in concatenate_images
    ret[dec[0]:dec[0] + shape[0], dec[1]:dec[1] + shape[1], :] = image
ValueError: could not broadcast input array from shape (1600,1600,4) into shape (1600,1600,3)
```

All works fine if I set `time_viewer=False`.

```
Platform:      macOS-11.4-x86_64-i386-64bit
Python:        3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:15)  [Clang 11.1.0 ]
Executable:    /Users/hoechenberger/miniforge3/envs/mne/bin/python3.9
CPU:           i386: 8 cores
Memory:        16.0 GB

mne:           0.24.dev0
numpy:         1.21.0 {blas=NO_ATLAS_INFO, lapack=lapack}
scipy:         1.7.0
matplotlib:    3.4.2 {backend=MacOSX}

sklearn:       0.24.2
numba:         Not found
nibabel:       3.2.1
nilearn:       0.8.0
dipy:          1.4.1
cupy:          Not found
pandas:        1.3.0
mayavi:        4.7.2
pyvista:       0.31.3 {pyvistaqt=0.5.0, OpenGL 4.1 INTEL-16.4.5 via Intel(R) Iris(TM) Plus Graphics 655}
vtk:           9.0.1
PyQt5:         5.12.3
```

cc @GuillaumeFavelier

**Comment by larsoner** [comment]
@GuillaumeFavelier this might be a nice break from the coreg refactoring :)
