### ISSUE TITLE
runtime warning in tutorial "iEEG localize" breaking docs build

### ISSUE THREAD

**Issue by drammock** [mne-tools/mne-python#9938]
@alexrockhill one for you?

```
Traceback (most recent call last):
  File "/home/circleci/project/tutorials/clinical/10_ieeg_localize.py", line 430, in <module>
    montage_warped, elec_image, warped_elec_image = mne.warp_montage_volume(
  File "<decorator-gen-56>", line 24, in warp_montage_volume
  File "/home/circleci/project/mne/surface.py", line 1902, in warp_montage_volume
    _warn_missing_chs(montage, image_to, after_warp=True)
  File "/home/circleci/project/mne/surface.py", line 1747, in _warn_missing_chs
    warn('Channels ' + ', '.join(missing_ch) + ' were not assigned '
  File "/home/circleci/project/mne/utils/_logging.py", line 365, in warn
    warnings.warn_explicit(
RuntimeWarning: Channels LAMY 1, LPM 8 were not assigned voxels after applying SDR warp
```

https://app.circleci.com/pipelines/github/mne-tools/mne-python/11144/workflows/f60acec5-586e-4508-a3a3-72ebbced8ce6/jobs/37417

**Comment by alexrockhill** [comment]
Sure, I'll have a look as soon as I can
